<a href="https://colab.research.google.com/github/AIWalaBro/Capstone_Project_ML/blob/main/Houses_Preprocessing/Houses_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
import warnings

# Suppress the SettingWithCopyWarning
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv('/content/houses.csv')
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [5]:
df.shape

(1044, 21)

In [6]:
# know the info
# check null
# check duplicated
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   object
 1   link             1044 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   rate             1005 non-null   object
 5   area             1044 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 171.4+ KB

In [7]:
df.isnull().sum()

property_name        0
link                 0
society            591
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     455
address             13
noOfFloor           77
facing             370
agePossession       57
nearbyLocations    131
description          8
furnishDetails     301
features           370
rating             137
property_id          8
dtype: int64

In [8]:
df.duplicated().sum()

13

# observation:-
- we found most of the columns are null values
- we found duplicated values
- most of the columns are in the object but you have to chnage it into float or int values

In [9]:
# lets drop the duplicates
df = df.drop_duplicates()

In [10]:
# now lets check once again shape of the data
df.shape

(1031, 21)

# Observation:-
- rows are reduced 1044 - 1031 = 13

In [11]:
df.columns

Index(['property_name', 'link', 'society', 'price', 'rate', 'area',
       'areaWithType', 'bedRoom', 'bathroom', 'balcony', 'additionalRoom',
       'address', 'noOfFloor', 'facing', 'agePossession', 'nearbyLocations',
       'description', 'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='object')

In [12]:
# we have to drop unnecessary columns
df.drop(columns = ['link','property_id'], inplace = True)

In [13]:
df.shape

(1031, 19)

In [14]:
# rename columns
df.rename(columns = {'rate':'price_per_sqft'}, inplace = True)

In [15]:
df.head(2)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN

# Society

In [16]:
df['society'].value_counts()

International City by SOBHA Phase 2                  26
Emaar MGF Marbella                                   26
Vipul Tatvam Villa                                   24
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             13
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Espace                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Not Applicable                                        7
Uppal Southend4.0 ★                                   7
Sushant Lok 1 Builder Floors                          6
Ansals Palam Vihar                                    6
DLF City Phase 1                                      5
Experion Windchants3.8 ★                              5
DLF Alameda                                           4
Unitech Aspen Greens                                  4
Ansal Sushant Lok Plots4.1 ★                          4
Vatika India Next4.1 ★                                4
nul                                                   4
Malibu Towne                                          3
Eros Rosewood City4.0 ★                               3
Rattan Garden                                         3
Housing Board Colony                                  3
BPTP Astaire Gardens3.7 ★                             3
SS Aaron Ville                                        3
Palam Vihar Extension West Zone RWA                   3
Unitech Nirvana Birch Court                           3
Puri Diplomatic Greens4.0 ★                           3
Vatika Signature Villas                               3
Eros Rosewood Villas                                  3
DLF City Plots Phase 3                                3
Central Park Flower Valley                            3
Sector 14 RWA                                         3
DLF New Town Heights 24.0 ★                           3
Anant Raj Estates                                     3
Tata Primanti4.1 ★                                    3
Ansals Florence Villa                                 3
Sobha City                                            2
Ardee City3.8 ★                                       2
Bestech Park View Ananda4.2 ★                         2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Unitech Escape3.8 ★                                   2
SS Hibiscus                                           2
Satya The Hermitage3.5 ★                              2
Hans Enclave                                          2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
Project Mianwali Colony                               2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Project Housing Board Colony                          2
Silverglades Tarudhan Valley Golf Resort              2
Spaze Privy3.9 ★                                      2
Suncity Essel Towers4.2 ★                             2
Luxury DLF City Floors                                2
Emaar Emerald Hills4.1 ★                              2
Ansal API Esencia3.7 ★                                2
shivpuri                                              2
Unitech Deerwood Chase                                2
Om Nagar, Sector-11                                   1
Central Park Flower Valley Cerise Floors              1
Kothi                                                 1
Birla Navya                                           1
Ansal API Spanish Court                               1
private house                                         1
4S Aradhya Homes                                      1
Sector-17C                                            1
Ireo Victory Valley4.1 ★                              1
Ansal Florence Super                                  1
Smart World Orchard                                   1
HUDA Ashok Vihar Phase 13.9 ★                         1
DLF City Plots Phase 4                                1
Ashok Vihar Phase 3 Gurgaon                           1
nirvana country                                       1
Landmark House                                        1
Farrukhnagar                                          1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
Ashok vihar phase III Extension                       1
Prem Kunj                                             1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
Unitech South City 23.8 ★                             1
DLF Floors Phase 3                                    1
huda sector-56 gurgaon                                1
Ireo Victory Valley4.0 ★                              1
Huda Floor                                            1
Huda                                                  1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Grover Homes Sec 4                                    1
DLF Pink Town House4.0 ★                              1
FLOOR WISE DESIGNER KOTHI                             1
Satya The Legend3.8 ★                                 1
Independent House Sector 45                           1
Adani Brahma Samsara4.2 ★                             1
sector 37                                             1
DLF New Town Heights3.7 ★                             1
All Punjabi Welfare Association                       1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF South City 1                                      1
Ansal Sushant Residency                               1
DLF City Plot Phase 3                                 1
sneh vihar                                            1
DLF The Arbour                                        1
mian wali                                             1
Ansal Celebrity Homes                                 1
Laxmi Garden Sector-11                                1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
Surat nagar phase 2                                   1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
ATS Tourmaline3.9 ★                                   1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
Bhawani enclave                                       1
DLF Garden City Floors                                1
Shri Shyam Residency                                  1
My Home                                               1
Sheetla Enclave                                       1
HUDA Plot Sector 38                                   1
Suncity Avenue 76                                     1
SS Omnia                                              1
secter 16a daultabad faridabad house no 313           1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
rajendra park sec 105                                 1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
Ansal Heights3.2 ★                                    1
Signature Global City 92                              1
DLF City Plot Phase 4                                 1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
Ninex City                                            1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
Signature Global Park4.0 ★                            1
ROW HOUSE                                             1
Name: society, dtype: int64

In [17]:
df['society'].value_counts().shape

(185,)

In [18]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [19]:
df['society'].value_counts()

nan                                                  586
emaar mgf marbella                                    26
international city by sobha phase 2                   26
vipul tatvam villa                                    24
international city by sobha phase 1                   23
unitech uniworld resorts                              13
dlf city plots                                        11
dlf city plots phase 2                                11
unitech espace                                        11
eldeco mansionz                                        9
bptp visionnaire                                       8
not applicable                                         7
uppal southend                                         7
sushant lok 1 builder floors                           6
ansals palam vihar                                     6
dlf city phase 1                                       5
experion windchants                                    5
dlf alameda                                            4
nul                                                    4
dlf new town heights                                   4
vatika india next                                      4
ansal sushant lok plots                                4
unitech aspen greens                                   4
ss aaron ville                                         3
eros rosewood villas                                   3
housing board colony                                   3
rattan garden                                          3
palam vihar extension west zone rwa                    3
vatika signature villas                                3
eros rosewood city                                     3
sector 14 rwa                                          3
ansals florence villa                                  3
malibu towne                                           3
central park flower valley                             3
dlf city plots phase 3                                 3
anant raj estates                                      3
tata primanti                                          3
unitech nirvana birch court                            3
puri diplomatic greens                                 3
bptp astaire gardens                                   3
unitech palms south city 1                             2
sector 38 rwa                                          2
iffco nagar and 17b rwa                                2
bhim garh kheri                                        2
sobha city                                             2
rwa sector 46                                          2
bptp pedestal                                          2
ardee city                                             2
ireo victory valley                                    2
unitech escape                                         2
satya the hermitage                                    2
ss hibiscus                                            2
suncity township                                       2
nirvana country                                        2
emaar the palm springs                                 2
nirvana cedar crest                                    2
saksham welfare association                            2
bestech park view ananda                               2
hans enclave                                           2
silverglades tarudhan valley golf resort               2
spaze privy                                            2
project housing board colony                           2
suncity essel towers                                   2
unitech deerwood chase                                 2
project mianwali colony                                2
luxury dlf city floors                                 2
shivpuri                                               2
emaar emerald hills                                    2
ansal api esencia                                      2
birla navya                                            1
farrukhnagar                                           1
kothi                                                  1
dlf the arbour                                         1
ashok vihar phase 3 gurgaon                            1
central park flower valley cerise floors               1
prem kunj                                              1
ansal api spanish court                                1
4s aradhya homes                                       1
private house                                          1
huda ashok vihar phase                                 1
secter 16a daultabad faridabad house no 313            1
dlf city plots phase 4                                 1
smart world orchard                                    1
landmark house                                         1
rajendra park sec 105                                  1
cloudnine cottages                                     1
u block dlf phase 3 road no 21                         1
sector 15 part 2 rwa                                   1
nitin vihar                                            1
ansal                                                  1
ashok vihar phase iii extension                        1
rattan vihar rajendra park                             1
signature global city 63a                              1
ansal florence super                                   1
ansal sushant residency                                1
unitech south city                                     1
sector-17c                                             1
huda floor                                             1
huda                                                   1
sector 57 huda                                         1
godrej meridien                                        1
ansal sushant lok 2                                    1
the laburnum                                           1
vatika independent floors                              1
arjun marg/ sector- 26 phase- 1/ golf course road      1
grover homes sec 4                                     1
dlf pink town house                                    1
floor wise designer kothi                              1
satya the legend                                       1
independent house sector 45                            1
sector 37                                              1
all punjabi welfare association                        1
unitech greenwood city                                 1
vatika the seven lamps                                 1
ansal sushant lok                                      1
central park                                           1
signature global city 81                               1
signature global city                                  1
dlf south city 1                                       1
huda sector-56 gurgaon                                 1
adani brahma samsara                                   1
dlf floors phase 3                                     1
dlf city plot phase 3                                  1
sheetla enclave                                        1
sneh vihar                                             1
house number b-34                                      1
mian wali                                              1
shri shyam residency                                   1
ansal celebrity homes                                  1
laxmi garden sector-11                                 1
huda housing board colony                              1
tulip yellow                                           1
shree krishna homes                                    1
smart world gems                                       1
ganpati heights apartment                              1
hero homes                                             1
jacobpura gurugram                                     1
anand garden, sector-105                               1
rk excelo                                              1
dlf gardencity enclave                                 1
dlf the grove                                          1
surendra homes dayanand colony                         1
ats tourmaline                                         1
bhawani enclave                                        1
om nagar, sector-11                                    1
vatika sovereign next                                  1
manohar nagar                                          1
anamika enclave                                        1
bhim nagar, sector 6                                   1
emaar mgf the palm drive                               1
tulip ivory                                            1
huda plots                                             1
rajendra park gurgaon                                  1
row house                                              1
dlf garden city floors                                 1
raj villas                                             1
suncity avenue 76                                      1
ss omnia                                               1
ansal heights                                          1
anshul                                                 1
sare crescent parc royal greens phase 1                1
ninex city                                             1
vipul world                                            1
greenopolis                                            1
ansal esencia sovereign floors                         1
nirmal enclave, maruti kunj road                       1
jacob pura                                             1
mahavir pura                                           1
shivaji nagar residential                              1
surat nagar phase 2                                    1
bhim nagar society                                     1
signature global park                                  1
signature global city 92                               1
dlf city plot phase 4                                  1
sai kripa floors 5                                     1
naman residency                                        1
krishna palace                                         1
my home                                                1
huda flats                                             1
jacobpura                                              1
indiabulls centrum park                                1
madan puri                                             1
huda plot sector 38                                    1
Name: society, dtype: int64

In [20]:
df['society'].isnull().sum()

0

In [21]:
df.isnull().sum()

property_name        0
society              0
price               76
price_per_sqft      39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     453
address             13
noOfFloor           76
facing             369
agePossession       57
nearbyLocations    131
description          8
furnishDetails     299
features           369
rating             137
dtype: int64

# Observation:-
- nan values are present in the society columns but no ableto see df
- we can do one thing nan values can be replace as independent

In [22]:
df['society'] = df['society'].str.replace('nan','independent')

In [23]:
df['society'].value_counts()

independent                                          586
emaar mgf marbella                                    26
international city by sobha phase 2                   26
vipul tatvam villa                                    24
international city by sobha phase 1                   23
unitech uniworld resorts                              13
dlf city plots                                        11
dlf city plots phase 2                                11
unitech espace                                        11
eldeco mansionz                                        9
bptp visionnaire                                       8
not applicable                                         7
uppal southend                                         7
sushant lok 1 builder floors                           6
ansals palam vihar                                     6
dlf city phase 1                                       5
experion windchants                                    5
dlf alameda                                            4
nul                                                    4
dlf new town heights                                   4
vatika india next                                      4
ansal sushant lok plots                                4
unitech aspen greens                                   4
ss aaron ville                                         3
eros rosewood villas                                   3
housing board colony                                   3
rattan garden                                          3
palam vihar extension west zone rwa                    3
vatika signature villas                                3
eros rosewood city                                     3
sector 14 rwa                                          3
ansals florence villa                                  3
malibu towne                                           3
central park flower valley                             3
dlf city plots phase 3                                 3
aindependentt raj estates                              3
tata primanti                                          3
unitech nirvana birch court                            3
puri diplomatic greens                                 3
bptp astaire gardens                                   3
unitech palms south city 1                             2
sector 38 rwa                                          2
iffco nagar and 17b rwa                                2
bhim garh kheri                                        2
sobha city                                             2
rwa sector 46                                          2
bptp pedestal                                          2
ardee city                                             2
ireo victory valley                                    2
unitech escape                                         2
satya the hermitage                                    2
ss hibiscus                                            2
suncity township                                       2
nirvana country                                        2
emaar the palm springs                                 2
nirvana cedar crest                                    2
saksham welfare association                            2
bestech park view aindependentda                       2
hans enclave                                           2
silverglades tarudhan valley golf resort               2
spaze privy                                            2
project housing board colony                           2
suncity essel towers                                   2
unitech deerwood chase                                 2
project mianwali colony                                2
luxury dlf city floors                                 2
shivpuri                                               2
emaar emerald hills                                    2
ansal api esencia                                      2
birla navya                                            1
farrukhnagar                                           1
kothi                                                  1
dlf the arbour                                         1
ashok vihar phase 3 gurgaon                            1
central park flower valley cerise floors               1
prem kunj                                              1
ansal api spanish court                                1
4s aradhya homes                                       1
private house                                          1
huda ashok vihar phase                                 1
secter 16a daultabad faridabad house no 313            1
dlf city plots phase 4                                 1
smart world orchard                                    1
landmark house                                         1
rajendra park sec 105                                  1
cloudnine cottages                                     1
u block dlf phase 3 road no 21                         1
sector 15 part 2 rwa                                   1
nitin vihar                                            1
ansal                                                  1
ashok vihar phase iii extension                        1
rattan vihar rajendra park                             1
signature global city 63a                              1
ansal florence super                                   1
ansal sushant residency                                1
unitech south city                                     1
sector-17c                                             1
huda floor                                             1
huda                                                   1
sector 57 huda                                         1
godrej meridien                                        1
ansal sushant lok 2                                    1
the laburnum                                           1
vatika independent floors                              1
arjun marg/ sector- 26 phase- 1/ golf course road      1
grover homes sec 4                                     1
dlf pink town house                                    1
floor wise designer kothi                              1
satya the legend                                       1
independent house sector 45                            1
sector 37                                              1
all punjabi welfare association                        1
unitech greenwood city                                 1
vatika the seven lamps                                 1
ansal sushant lok                                      1
central park                                           1
signature global city 81                               1
signature global city                                  1
dlf south city 1                                       1
huda sector-56 gurgaon                                 1
adani brahma samsara                                   1
dlf floors phase 3                                     1
dlf city plot phase 3                                  1
sheetla enclave                                        1
sneh vihar                                             1
house number b-34                                      1
mian wali                                              1
shri shyam residency                                   1
ansal celebrity homes                                  1
laxmi garden sector-11                                 1
huda housing board colony                              1
tulip yellow                                           1
shree krishna homes                                    1
smart world gems                                       1
ganpati heights apartment                              1
hero homes                                             1
jacobpura gurugram                                     1
aindependentd garden, sector-105                       1
rk excelo                                              1
dlf gardencity enclave                                 1
dlf the grove                                          1
surendra homes dayaindependentd colony                 1
ats tourmaline                                         1
bhawani enclave                                        1
om nagar, sector-11                                    1
vatika sovereign next                                  1
manohar nagar                                          1
anamika enclave                                        1
bhim nagar, sector 6                                   1
emaar mgf the palm drive                               1
tulip ivory                                            1
huda plots                                             1
rajendra park gurgaon                                  1
row house                                              1
dlf garden city floors                                 1
raj villas                                             1
suncity avenue 76                                      1
ss omnia                                               1
ansal heights                                          1
anshul                                                 1
sare crescent parc royal greens phase 1                1
ninex city                                             1
vipul world                                            1
greenopolis                                            1
ansal esencia sovereign floors                         1
nirmal enclave, maruti kunj road                       1
jacob pura                                             1
mahavir pura                                           1
shivaji nagar residential                              1
surat nagar phase 2                                    1
bhim nagar society                                     1
signature global park                                  1
signature global city 92                               1
dlf city plot phase 4                                  1
sai kripa floors 5                                     1
naman residency                                        1
krishna palace                                         1
my home                                                1
huda flats                                             1
jacobpura                                              1
indiabulls centrum park                                1
madan puri                                             1
huda plot sector 38                                    1
Name: society, dtype: int64

In [24]:
df.head(3)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

#Price

In [25]:
df['price'].value_counts()

3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
5 Crore             13
4.5 Crore           13
70 Lac              13
8 Crore             13
50 Lac              13
75 Lac              13
8.5 Crore           12
7 Crore             12
85 Lac              12
1.5 Crore           11
4 Crore             11
10 Crore            10
Price on Request    10
45 Lac              10
2.25 Crore          10
2.5 Crore           10
60 Lac              10
90 Lac              10
9 Crore             10
9.5 Crore            9
12 Crore             9
80 Lac               9
1.7 Crore            9
2 Crore              9
1.1 Crore            9
1 Crore              8
6.75 Crore           8
11 Crore             8
1.6 Crore            8
4.6 Crore            8
1.3 Crore            7
95 Lac               7
12.5 Crore           7
3.75 Crore           7
1.2 Crore            7
55 Lac               7
2.1 Crore            7
65 Lac               7
40 Lac               7
1.35 Crore           7
1.15 Crore           6
10.5 Crore           6
4.25 Crore           6
7.5 Crore            6
16 Crore             6
3.25 Crore           6
2.95 Crore           6
5.7 Crore            6
2.75 Crore           6
13.5 Crore           6
3.6 Crore            6
1.45 Crore           6
6.25 Crore           6
38 Lac               5
3 Crore              5
4.75 Crore           5
15 Crore             5
35 Lac               5
5.6 Crore            5
1.8 Crore            5
1.25 Crore           5
2.8 Crore            5
7.25 Crore           5
42 Lac               4
2.4 Crore            4
1.65 Crore           4
4.35 Crore           4
4.7 Crore            4
18 Crore             4
9.25 Crore           4
37 Lac               4
5.25 Crore           4
1.4 Crore            4
8.25 Crore           4
5.75 Crore           4
11.5 Crore           4
6.8 Crore            4
17 Crore             4
3.2 Crore            4
5.8 Crore            4
13 Crore             4
3.3 Crore            4
1.16 Crore           3
2.3 Crore            3
82 Lac               3
1.9 Crore            3
5.65 Crore           3
7.35 Crore           3
4.3 Crore            3
92 Lac               3
1.85 Crore           3
34 Lac               3
3.4 Crore            3
32 Lac               3
49 Lac               3
5.15 Crore           3
62 Lac               3
8.4 Crore            3
2.2 Crore            3
19 Crore             3
4.45 Crore           3
6.95 Crore           3
6.4 Crore            3
20 Crore             3
1.95 Crore           3
3.1 Crore            3
7.2 Crore            3
2.9 Crore            3
1.55 Crore           3
3.85 Crore           3
9.9 Crore            2
11.75 Crore          2
7.1 Crore            2
4.95 Crore           2
14 Crore             2
8.49 Crore           2
1.05 Crore           2
3.51 Crore           2
3.35 Crore           2
89 Lac               2
10.85 Crore          2
26 Crore             2
58.25 Lac            2
3.65 Crore           2
10.55 Crore          2
15.5 Crore           2
3.15 Crore           2
2.15 Crore           2
6.3 Crore            2
2.55 Crore           2
11.25 Crore          2
36 Lac               2
66 Lac               2
48 Lac               2
1.75 Crore           2
11.95 Crore          2
67 Lac               2
58 Lac               2
19.5 Crore           2
3.05 Crore           2
3.55 Crore           2
30 Lac               2
10.45 Crore          2
6.15 Crore           1
2.47 Crore           1
55.11 Lac            1
3.7 Crore            1
8.45 Crore           1
4.4 Crore            1
99 Lac               1
2.65 Crore           1
1.27 Crore           1
11.29 Crore          1
7.05 Crore           1
4.31 Crore           1
18.4 Crore           1
3.69 Crore           1
10.3 Crore           1
9.4 Crore            1
7.3 Crore            1
18.5 Crore           1
5.85 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
4.02 Crore           1
5.1 Crore            1
3.9 Crore            1
2.01 Crore           1
5.88 Crore           1
52.75 Lac            1
46.75 Lac            1
12.25 Crore          1
11.3 Crore           1
8.48 Crore           1
11.58 Crore          1
3.49 Crore           1
8.2 Crore            1
61 Lac               1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
5.35 Crore           1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
4.99 Crore           1
9.8 Crore            1
5.51 Crore           1
9.01 Crore           1
4.15 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
1.04 Crore           1
9.85 Crore           1
1.18 Crore           1
15.1 Crore           1
5.9 Crore            1
3.99 Crore           1
22 Crore             1
47 Lac               1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
5.2 Crore            1
7.99 Crore           1
42.75 Lac            1
71 Lac               1
7.6 Crore            1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
10.75 Crore          1
29 Lac               1
4.12 Crore           1
52 Lac               1
4.49 Crore           1
53 Lac               1
7.5 Lac              1
2.58 Crore           1
7.49 Crore           1
22 Lac               1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
63 Lac               1
1.87 Crore           1
1.72 Crore           1
5.46 Crore           1
12.39 Crore          1
78 Lac               1
1.52 Crore           1
10.56 Crore          1
5.4 Crore            1
24 Lac               1
44 Lac               1
83 Lac               1
17.3 Crore           1
3.93 Crore           1
27 Lac               1
8.1 Crore            1
8.7 Crore            1
14.75 Crore          1
9.54 Crore           1
6.2 Crore            1
18.9 Crore           1
98 Lac               1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.12 Crore           1
6.81 Crore           1
8.81 Crore           1
8.9 Crore            1
7.69 Crore           1
59 Lac               1
1.39 Crore           1
3.87 Crore           1
15.5 Lac             1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
13 Lac               1
96 Lac               1
6.6 Crore            1
18.02 Crore          1
65.8 Lac             1
8.8 Crore            1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
2.98 Crore           1
Name: price, dtype: int64

In [26]:
# we noticed that Price on Request are in the value_counts
df = df[df['price'] != 'Price on Request']

In [27]:
df.shape

(1021, 19)

#### Observation:- we noticed we left 1021 rows

In [28]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [29]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [30]:
df['price']

0        5.25
1        5.70
2        2.10
3        5.00
4        3.00
5        4.50
6       12.00
7       20.00
8       10.85
9        1.95
10       4.45
11       9.00
12       5.00
13      15.00
14       8.25
15       2.00
16      10.75
17       2.10
18       7.35
19       4.45
20       3.40
21      12.00
22       8.40
23       8.50
24       7.60
25       7.00
26       4.75
27       3.50
28       5.00
29      10.56
30       5.46
31      10.00
32       9.00
33      10.00
34       1.95
35       3.30
36      13.00
37       7.20
38       6.00
39       9.00
40       5.80
41       0.55
42       7.49
43      13.50
44      11.95
45      12.39
46       6.25
47        NaN
48       5.40
49       5.75
50       2.55
51       5.60
52      17.00
53       7.99
54       3.75
55       7.25
56       8.40
57       3.55
58       2.50
59       2.50
60       9.00
61       2.10
62        NaN
63        NaN
64       4.50
65       6.50
66        NaN
67        NaN
68        NaN
69        NaN
70        NaN
71        NaN
72        NaN
73        NaN
74        NaN
75        NaN
76        NaN
77        NaN
78        NaN
79       9.50
80       5.00
81        NaN
82        NaN
83        NaN
84        NaN
85        NaN
86        NaN
87        NaN
88        NaN
89        NaN
90       5.50
91       5.65
92        NaN
93        NaN
94        NaN
95        NaN
96        NaN
97        NaN
98        NaN
99        NaN
100       NaN
101      8.80
102       NaN
103       NaN
104       NaN
105       NaN
106      3.25
107      5.00
108     10.45
109     19.50
110       NaN
111       NaN
112      7.50
113      0.67
114      5.75
115       NaN
116      5.70
117      3.20
118     11.50
119      7.69
120      7.00
121      1.55
122      3.85
123      2.00
124      3.10
125      2.25
126      7.00
127      8.50
128      8.70
129     12.50
130      6.80
131      9.50
132      7.00
133      6.20
134      3.60
135      3.05
136      5.90
137      5.85
138      4.00
139      5.35
140      6.60
141      6.30
142     12.00
143      0.65
144      0.55
145      0.85
146      0.58
147      0.65
148      0.61
149      0.67
150      5.80
151      6.00
152      6.25
153      7.05
154      4.50
155      3.69
156      2.50
157      5.50
158     15.00
159      6.95
160      5.70
161     11.30
162     11.25
163      4.02
164      5.70
165      1.00
166      0.66
167      0.70
168      1.45
169      0.95
170      4.50
171      0.90
172      0.45
173      1.00
174      0.60
175      7.00
176      3.93
177      4.00
178      0.75
179      0.90
180      2.75
181      0.50
182      0.50
183      0.42
184      0.60
185      0.48
186      0.50
187      0.35
188      4.00
189      2.40
190      2.20
191      1.10
192      8.00
193      0.82
194      0.90
195      0.70
196      0.95
197      1.30
198      0.36
199      3.50
200      0.80
201      0.15
202      0.80
203      6.00
204      2.80
205      2.75
206      1.75
207      3.10
208      1.16
209      0.85
210      0.90
211      0.34
212      5.00
213      0.36
214      5.00
215      9.50
216      7.25
217      1.50
218      1.30
219      3.75
220      0.37
221      2.25
222      1.15
223      0.95
224      0.49
225      1.45
226      0.80
227      1.60
228      0.85
229      7.00
230      0.50
231      8.00
232      0.45
233      0.62
234      1.00
235      4.12
236      0.95
237      0.45
238      0.45
239      1.87
240      0.85
241      0.42
242      0.42
243      1.20
244      6.50
245      3.75
246      2.50
247      2.25
248      0.75
249      0.30
250       NaN
251      1.35
252      4.70
253      0.60
254      0.22
255      1.65
256      0.50
257      2.30
258      1.25
259      1.70
262      6.00
263      2.80
264      3.12
265      0.07
266      3.50
267      2.58
268      8.50
269      4.00
270      1.45
271      0.60
272      1.10
273       NaN
274      2.50
275      3.50
276      2.95
277       NaN
278       NaN
279      0.70
280      1.16
281     16.00
282      8.50
283      8.95
284       NaN
285     14.00
286      0.85
287      1.35
288     13.20
289      6.00
292       NaN
293       NaN
294       NaN
295       NaN
296       NaN
297      0.51
298      1.10
299       NaN
300      2.50
301      0.53
302      2.00
303      0.63
304      8.00
305      0.45
306      0.37
307      1.72
308      1.35
309      0.50
310      0.62
311      8.00
312      1.80
313      1.70
314      0.55
315      1.50
316      1.55
317      0.32
318       NaN
319       NaN
320       NaN
321       NaN
322      2.10
323      5.60
324       NaN
325       NaN
326       NaN
327      0.65
328      1.60
329      0.78
330      0.95
331      3.85
332      0.66
333      0.45
334      0.85
335      1.50
336      1.52
337      1.00
338      1.05
339      0.85
340      0.58
341      0.45
342      1.35
343      0.70
344      1.40
345      5.15
346      6.50
347      3.50
348     13.50
349      5.70
350      3.30
351      1.75
352      0.75
353      3.50
354      0.92
356      0.52
357      1.10
358      0.75
359      1.25
360      4.25
361      0.37
362      5.70
363      0.80
364      2.10
365      1.10
366      0.60
367      1.20
368      4.50
369      0.80
370      1.10
371       NaN
372      3.00
373      8.50
374      1.10
375      0.75
376      6.00
377      0.82
378      0.35
379      1.15
380      1.85
381      8.50
382      0.90
383      0.50
385      5.75
386      4.65
387      7.20
388      0.60
389      4.50
390      1.30
391      3.20
392      0.60
393      1.95
394      1.25
395      6.10
396      0.50
397      2.00
398      2.10
399      1.25
400      0.65
401     11.50
402      0.90
403      0.75
404      1.30
405      0.48
406      0.68
407      1.50
408      1.30
409      0.60
410      6.50
411      0.49
412      1.07
413      2.10
414      4.60
415      1.00
416      1.10
417      2.95
418      4.60
419      0.35
420      1.50
421     10.00
422      5.20
423      0.40
424      0.62
425      0.50
426      5.00
427      0.92
428      3.50
429      0.80
430      1.50
431      2.25
432     13.50
433      0.50
434      1.70
435      0.45
436       NaN
437      1.20
438      1.80
439      1.50
440      0.35
441      0.55
442      4.30
443      0.40
444       NaN
445      3.00
446      0.43
448      0.32
449      0.47
450      5.50
451      0.75
452      0.71
453      0.38
454      3.25
455      0.53
456      2.30
457      1.50
458      1.10
459      1.35
460      1.30
461      1.25
462       NaN
463      1.44
464      0.50
465      1.00
466      5.50
467      5.50
468      0.80
469      0.90
470      4.30
471      0.90
472      3.25
473      0.38
474      3.71
475     13.00
476      0.40
477      0.55
478      1.30
479      0.75
480      0.30
481      0.18
482      1.55
483      0.32
484      4.00
485      0.38
486     12.00
487      8.00
488      0.45
489      1.20
490      0.40
491      1.00
492      0.50
493      1.15
494      0.70
495      3.08
496      2.95
497      8.00
498      6.50
499      3.00
500      8.00
501      2.75
502      2.25
503      1.45
504      3.50
505      0.82
506     10.50
507      0.38
508     10.00
509      0.75
510      4.60
511      0.50
512      7.00
513      0.35
514      0.95
515      1.60
516      0.29
517      0.24
518      5.60
519      0.55
520      5.00
521      1.80
523      1.50
524      1.05
525      1.80
526      0.44
527      0.83
528      0.70
529      0.98
530      3.35
531      0.47
532      1.20
533      9.00
534      3.09
535      3.15
536      1.70
537      4.75
538      1.65
539      0.85
540      2.00
541      0.74
542      1.85
543      0.40
544      0.85
545      0.69
546      0.85
547     13.00
549      1.40
550      1.80
551      0.70
552      0.70
553      2.40
554      3.35
555      7.00
556      1.65
557      0.60
558      2.43
559      3.50
560      0.34
561      0.75
562      0.55
563      0.70
564      6.25
565      1.20
566      0.49
567      2.00
568      0.37
569      0.42
570      0.75
571      3.50
572      4.50
573      1.16
574      0.90
575      0.75
576      0.13
577      0.96
578      1.35
579      0.65
580     11.00
581     18.02
582      0.66
583      4.60
584       NaN
585      1.90
586      1.50
587      2.50
588      0.70
589      0.85
590      2.00
591      0.70
592      0.89
593      0.80
594      1.60
595      0.89
596      1.34
597      1.70
598      0.34
599      9.90
600      0.40
601      2.15
602      1.85
603      0.45
604      0.58
605      1.70
606      0.46
607      0.80
608      0.58
609      2.60
610      2.00
611      3.87
612      0.65
613      2.25
614      0.85
615      2.00
616     10.00
617      3.50
618      0.55
619      6.50
620      1.39
622      0.70
623      0.59
624      4.00
625     12.50
626      1.60
627      1.60
628      2.90
629      0.40
630      1.70
631      5.50
632      6.75
633      5.50
634      2.75
635      0.27
636      0.70
637      0.95
638      8.10
639      7.00
640      0.38
641      0.60
642      0.65
643      7.20
644      1.50
645     10.00
646     15.50
647     14.75
648     20.00
649      9.54
650     10.55
651     17.30
652      3.65
653     18.90
654      9.00
655     24.00
656      2.15
657      2.25
658      7.46
659      6.75
660      0.60
661      3.99
662      6.81
663      6.50
664      6.95
665      7.00
666      3.85
667      3.20
668      8.81
669      1.45
670      8.90
671      6.50
672      4.49
673     22.00
674      9.50
675      7.00
676      4.15
677      2.90
678     12.00
679      8.50
680     11.00
681      1.35
682      1.90
683      3.25
684     19.00
685      7.30
686      5.60
687      2.55
688      2.40
689     18.50
690     26.00
691      1.70
692      1.60
693      4.35
694      6.80
695     10.00
696      4.60
697     12.50
698      2.90
699     27.50
700      8.00
701      2.25
702      8.31
703      6.21
704      7.35
705      4.50
706      6.50
707      1.83
708      7.35
709     10.50
710      2.75
711      6.50
712      7.50
713      8.00
714      5.50
715      4.35
716      2.75
717     18.00
718     17.00
719      3.75
720     13.50
721      4.75
722      5.10
723      3.90
724      6.25
725     10.55
726      2.01
727      3.25
728      9.25
729      6.00
730      5.25
731       NaN
732     26.00
733      5.88
734      0.53
735      0.47
736     12.25
737     10.45
738     12.00
739       NaN
740      6.40
741      4.35
742      2.95
743      3.00
744      1.15
745      8.25
746     13.50
747     15.00
748      5.50
749     18.00
750      5.80
751     12.50
752      3.51
753      3.50
754      9.40
755     10.30
756      6.00
757      8.45
758      7.25
759      4.00
760      6.15
761      4.60
762     12.50
763     10.00
764     16.00
765     12.50
766     16.00
767     10.00
768       NaN
769      2.80
770      6.75
771      2.50
772      8.00
785      2.47
786      3.70
787     18.40
788      4.60
789      3.65
790     12.00
791      4.50
792      4.40
793      7.25
794      0.99
795       NaN
796     20.00
797      2.65
798      2.95
799      3.60
800      1.27
801      0.75
802      6.00
803       NaN
804      6.50
805     18.00
806     11.29
807      8.49
808      8.50
809      6.00
810      9.50
811     19.50
812     10.50
813      4.31
814      6.95
815     10.50
816     10.50
817      5.80
818      4.60
819     11.58
820       NaN
821      4.00
822     16.00
823      6.00
825      6.80
826      2.50
827      7.50
828      8.48
829      6.25
830     10.85
831      5.15
832      3.50
833      3.60
834      6.00
835     14.00
836      1.60
837      1.70
838      7.25
839     15.50
840      3.40
841     11.25
842      3.30
843      5.50
844       NaN
845      8.50
846      8.50
847       NaN
848     11.95
849     12.00
850      6.50
851     17.00
852     11.50
853      9.00
854     15.00
855      8.20
856      5.51
857      3.20
858      8.00
859      2.95
860      2.80
861      5.25
862      8.49
863      4.35
864      3.49
865      2.99
866      9.19
867      1.64
868      9.35
869      9.25
870      2.80
871      2.50
872      4.05
873      8.40
874      6.00
875     11.00
876      8.75
877     23.00
878      6.50
879      2.45
880      5.50
881      3.51
882      9.25
883      5.65
884      7.85
885     13.50
886     19.00
887      5.50
888      3.50
889      8.25
890     16.00
891     25.00
892      2.68
893      2.70
894      2.30
895      0.92
896      1.04
897      9.85
898     15.00
899      1.18
900      0.90
901     13.00
902     15.10
903      9.01
904     18.00
905     12.00
906      2.25
907      8.00
908      5.75
909      9.80
910      4.95
911     19.00
912      4.99
913      7.10
914      4.25
915      9.50
916     16.00
917      8.25
918      4.70
919      4.25
920       NaN
921      4.50
922      8.60
923      9.55
924      4.95
925      9.50
926      5.00
927      4.75
928      1.15
929      6.00
930      9.00
931      3.60
932      9.00
933      2.20
934      3.30
935      3.50
936      2.35
937     18.25
938      5.30
939      6.25
940      6.30
941      5.50
942     11.75
943      1.90
944     10.80
945      6.40
946      1.15
947      5.50
948      3.50
949      3.75
950      4.25
951      4.00
952     31.50
953      1.40
954      5.00
955     17.00
956      9.00
957      1.65
958     11.00
959     11.00
960      3.75
961      3.40
962      4.50
963      5.25
964      6.50
965     11.00
966      7.50
967      9.90
968      6.75
969      6.75
970      3.75
971      1.45
972      4.10
973      6.40
974      3.50
975      4.70
976      7.50
977      5.50
978      7.65
979      5.15
980      6.75
981     10.00
982      8.50
983      6.75
984      9.50
985      5.50
986      6.46
987      5.60
988     10.50
989      8.00
990      6.44
991      7.50
992      7.00
993     11.00
994      6.50
995      6.80
996      6.75
997      4.70
998      7.80
999      6.50
1000     8.50
1001     4.50
1002     4.45
1003      NaN
1004     3.80
1005     1.00
1006     1.40
1007    11.50
1008     3.50
1009     7.10
1010     9.50
1011    11.75
1012     4.00
1013     2.25
1014    12.50
1015    11.00
1016     4.30
1017     7.45
1018     7.42
1019     9.25
1020     1.20
1021     6.09
1022     5.00
1023      NaN
1024      NaN
1025     2.98
1026     4.00
1027     2.40
1028     3.15
1029     4.25
1030     5.00
1031     2.20
1032     3.50
1033     5.65
1034     3.55
1035     3.60
1036     3.10
1037     4.75
1038     3.05
1039     5.50
1040     4.25
1041     4.50
1042     3.25
1043     3.60
Name: price, dtype: float64

# price_per_sqft

In [41]:
df['price_per_sqft'].value_counts()

₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     11
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 26,667/sq.ft.      6
₹ 13,333/sq.ft.      6
₹ 37,037/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 9,444/sq.ft.       5
₹ 23,333/sq.ft.      5
₹ 23,148/sq.ft.      5
₹ 11,100/sq.ft.      5
₹ 8,000/sq.ft.       5
₹ 8,889/sq.ft.       5
₹ 5,000/sq.ft.       5
₹ 35,000/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 18,889/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 6,944/sq.ft.       4
₹ 36,111/sq.ft.      3
₹ 13,889/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 16,058/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 60,000/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 14,815/sq.ft.      3
₹ 12,000/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 15,555/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 7,500/sq.ft.       3
₹ 11,250/sq.ft.      3
₹ 15,625/sq.ft.      3
₹ 25,926/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 32,222/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 50,000/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 12,500/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 7,407/sq.ft.       2
₹ 35,185/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 100,000/sq.ft.     2
₹ 9,000/sq.ft.       2
₹ 20,635/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 35,556/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 44,444/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 75,000/sq.ft.      2
₹ 21,759/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 17,037/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 8,888/sq.ft.       2
₹ 4,444/sq.ft.       2
₹ 17,778/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 24,500/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 13,622/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 20,988/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 18,888/sq.ft.      1
₹ 20,741/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 36,911/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 18,444/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 234,375/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 26,298/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 22,812/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 178,571/sq.ft.     1
₹ 23,240/sq.ft.      1
₹ 27,461/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 47,803/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,127/sq.ft.       1
₹ 7,000/sq.ft.       1
₹ 14,166/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 7,777/sq.ft.       1
₹ 18,658/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 7,555/sq.ft.       1
₹ 6,289/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 10,610/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 8,155/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 17,857/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 28,787/sq.ft.      1
₹ 20,444/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 20,026/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 24,074/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 31,915/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 5,777/sq.ft.       1
₹ 15,926/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 23,442/sq.ft.      1
₹ 33,665/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 6,230/sq.ft.       1
₹ 23,889/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 5,128/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 144,444/sq.ft.     1
₹ 20,349/sq.ft.      1
₹ 9,615/sq.ft.       1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 8,920/sq.ft.       1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 19,360/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 18,620/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 14,667/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 15,432/sq.ft.      1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 19,231/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 17,187/sq.ft.      1
₹ 7,718/sq.ft.       1
₹ 25,535/sq.ft.      1
₹ 1,859/sq.ft.       1
₹ 10,579/sq.ft.      1
₹ 42,194/sq.ft.      1
₹ 15,278/sq.ft.      1
₹ 201,388/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 18,928/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 16,056/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 40,850/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 21,786/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 14,222/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 19,125/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 19,645/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 6,800/sq.ft.       1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 7,333/sq.ft.       1
₹ 20,115/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,701/sq.ft.       1
₹ 4,117/sq.ft.       1
₹ 7,309/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,695/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 8,411/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 14,890/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 13,542/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 14,729/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 17,650/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 38,667/sq.ft.      1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,619/sq.ft.       1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 20,062/sq.ft.      1
₹ 98,214/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 19,818/sq.ft.      1
₹ 6,481/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,397/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 17,500/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 3,254/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,333/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 8,642/sq.ft.       1
₹ 10,122/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 22,297/sq.ft.      1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 5,658/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 8,796/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 6,567/sq.ft.       1
₹ 66,666/sq.ft.      1
₹ 19,869/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 120,000/sq.ft.     1
₹ 125,000/sq.ft.     1
₹ 37,313/sq.ft.      1
₹ 73,333/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 11,718/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 35,494/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 33,129/sq.ft.      1
Name: price_per_sqft, dtype: int64

In [42]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹'," ").str.replace(',','').str.strip().astype(float)

In [43]:
df['price_per_sqft'].dtype

dtype('float64')

In [44]:
df['price_per_sqft'].isnull().sum()
# nan values are there

29

# observation:- 29 null values are there

# Bedrooms

In [45]:
df['bedRoom'].value_counts()

4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: bedRoom, dtype: int64

In [35]:
# df['bedRoom'].str.get(0)

# Nan values are there

In [47]:
df[df['bedRoom'].isnull()].shape

(57, 19)

In [48]:
df = df[~df['bedRoom'].isnull()]

In [49]:
df.shape

(964, 19)

# observation:-
- we remove null values and 964 rows

In [52]:
df['bedRoom'] = df['bedRoom'].str.get(0).astype('int')

In [54]:
df['bedRoom'].shape

(964,)

In [55]:
df.shape

(964, 19)

#Bathroom

In [56]:
df['bathroom'].value_counts()

4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: bathroom, dtype: int64

In [57]:
df['bathroom'].isnull().sum()

0

In [61]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [62]:
df['bathroom']

0        4
1        4
2       10
3       21
4       12
5       20
6        5
7       16
8        6
9        4
10       3
11       7
12      13
13       6
14       6
15       4
16       9
17       7
18       4
19       6
20       9
21       6
22       4
23       4
24       9
25       5
26       5
27       9
28       9
29       5
30       5
31       6
32      10
33       4
34       2
35       4
36      16
37       3
38       4
39       5
40       5
41       1
42      12
43      16
44      12
45      18
46       5
47       5
48       5
49       4
50       3
51       6
52       8
53       6
54       6
55       4
56       5
57       4
58       4
59       4
60       5
61       3
64       5
65       4
79      12
80       4
90       4
91       4
101      4
106      3
107      3
108      5
109      6
112      5
113      2
114      4
116      5
117      3
118     13
119      5
120      4
121      2
122      4
123      2
124      3
125      3
126      4
127      5
128      5
129      6
130      5
131      6
132      6
133      5
134      5
135      5
136      5
137      5
138      4
139      4
140      7
141      5
142      6
143      2
144      3
145      3
146      2
147      1
148      2
149      3
150      6
151      5
152      9
153     18
154     16
155      4
156      7
157      1
158      4
159      3
160      5
161      5
162      5
163      4
164      4
165      7
166      1
167      2
168      3
169      3
170      9
171      1
172      2
173      3
174      4
175      7
176     17
177      4
178      1
179      4
180      7
181      4
182      3
183      2
184      3
185      2
186      3
187      2
188      3
189      4
190      3
191      8
192      5
193      3
194      3
195      4
196      3
197      4
198      1
199      6
200      8
201      1
202      5
203      5
204      7
205      4
206      4
207      5
208      4
209      2
210      4
211      2
212      6
213      2
214      3
215      7
216      8
217      3
218      2
219      5
220      3
221     10
222      3
223      2
224      3
225      4
226      2
227      5
228      6
229      5
230      2
231     10
232      2
233      6
234      4
235      1
236      6
237      3
238      3
239      4
240      1
241      3
242      3
243      4
244      6
245      4
246      2
247     36
248      2
249      3
250      4
251      3
252      3
253      2
254      2
255      9
256      3
257      6
258      6
259      1
262      4
263      4
264      2
265      1
266      3
267      2
268      4
269      7
270      3
271      3
272      3
274      5
275      2
276      2
279      2
280      4
281      5
282     12
283      6
285      9
286      2
287      5
288      6
289      9
297      4
298      4
299      2
300      5
301      2
302      2
303      2
304     10
305      1
306      2
307      3
308      6
309      2
310      1
311      9
312      5
313      4
314      1
315      1
316      2
317      2
322      3
323     34
327      2
328      6
329      4
330      1
331      6
332      2
333      4
334      2
335      2
336      2
337      2
338      2
339      3
340      2
341      2
342      3
343      2
344      2
345      5
346      5
347      5
348      9
349      9
350      1
351      2
352      2
353      8
354      1
356      2
357      4
358      4
359      3
360      3
361      1
362      4
363      6
364      2
365      4
366      3
367      4
368      4
369      4
370      2
371      1
372      4
373      6
374      3
375      4
376      6
377      4
378      4
379      2
380      3
381      6
382      5
383      1
385      4
386      5
387      4
388      3
389      5
390      2
391     14
392      3
393      5
394      6
395      6
396      3
397      1
398      8
399      3
400      2
401      6
402      4
403      4
404      3
405      2
406      3
407      2
408      3
409      2
410      4
411      1
412      2
413      6
414      2
415      4
416      4
417      3
418      4
419      2
420      9
421     10
422      5
423      1
424      3
425      3
426      5
427      4
428      6
429      4
430      3
431      5
432      6
433      4
434      1
435      2
436      3
437      2
438      3
439      3
440      2
441      2
442     13
443      1
444      4
445      4
446      3
448      3
449      1
450      9
451      5
452      2
453      2
454      3
455      4
456      3
457      7
458      3
459      5
460      4
461      5
462      2
463      2
464      2
465      7
466      9
467      3
468      3
469      4
470      4
471      5
472      4
473      1
474      3
475     10
476      2
477      4
478      3
479      2
480      1
481      1
482      3
483      1
484      4
485      2
486      6
487      1
488      1
489      3
490      2
491      1
492      2
493      2
494      3
495      4
496      2
497      5
498      3
499      7
500      5
501      6
502      3
503      2
504      3
505      2
506      4
507      3
508      6
509      3
510      6
511      1
512     11
513      1
514      3
515      1
516      1
517      2
518      3
519      2
520      4
521      1
523      3
524      3
525      5
526      2
527      3
528      2
529      4
530      5
531      4
532      4
533      5
534      5
535      5
536      3
537      7
538      3
539      4
540      3
541      3
542      3
543      1
544      3
545      1
546      2
547      8
549      2
550      5
551      4
552      3
553      5
554      1
555      2
556      1
557      1
558      4
559      1
560      1
561      4
562      1
563      2
564      3
565      4
566      2
567     10
568      1
569      3
570      1
571      1
572      5
573      1
574      4
575      2
576      1
577      4
578      5
579      1
580     11
581     12
582      2
583      1
584      5
585      3
586      3
587      4
588      2
589      5
590      9
591      1
592      3
593      1
594      2
595      1
596      1
597      5
598      1
599      2
600      4
601      1
602      8
603      2
604      3
605      4
606      3
607      4
608      3
609      4
610      5
611     17
612      3
613      2
614      2
615     10
616      5
617      4
618      1
619      2
620      2
622      3
623      2
624      5
625      5
626      5
627      5
628      7
629      4
630      2
631      3
632      4
633      3
634      3
635      2
636      3
637     10
638      5
639      4
640      1
641      3
642      2
643      4
644      5
645      7
646      6
647     20
648     20
649      5
650      6
651      7
652      9
653      8
654      5
655      5
656      3
657      3
658      4
659     12
660      4
661      5
662     14
663      5
664      4
665      5
666      3
667      4
668      6
669      4
670      4
671      9
672      9
673      6
674      5
675      4
676      4
677      4
678      6
679      6
680      4
681      2
682      3
683      6
684      6
685      9
686      4
687      3
688      3
689      4
690     16
691      1
692      4
693      4
694      4
695     12
696      3
697      4
698      4
699      7
700      9
701     11
702      6
703      6
704      4
705      3
706      3
707      4
708      5
709      4
710      3
711     12
712      9
713      7
714      8
715      4
716      3
717      6
718      6
719      4
720      5
721      5
722      2
723      6
724      4
725      5
726      3
727      4
728     12
729      4
730      4
731     12
732      7
733      9
734      1
735      2
736      7
737      7
738      4
739      8
740      4
741      8
742      4
743      4
744      3
745     12
746      5
747      5
748      7
749      4
750      3
751      4
752      4
753      5
754      6
755      6
756      4
757      3
758      8
759      3
760      5
761      4
762      5
763      5
764      6
765      5
766      7
767      6
768      7
769      5
770      3
771      4
772      4
785      4
786      8
787      8
788      6
789      6
790      5
791      8
792      6
793      4
794      4
795      7
796      7
797      3
798      4
799      4
800      3
801      2
802      6
803     16
804      5
805      6
806      5
807      3
808      4
809      4
810      5
811      9
812     12
813      4
814     12
815      4
816      5
817      4
818      4
819      5
820      5
821      4
822      7
823      5
825      5
826      5
827     12
828      6
829      7
830      8
831      9
832      4
833      4
834      5
835      5
836      4
837      3
838      9
839      6
840      3
841      9
842      3
843      8
844      9
845      5
846      4
848      3
849      4
850      4
851      8
852      8
853     12
854      4
855      3
856      3
857      3
858      7
859      3
860      3
861      9
862     12
863      4
864      4
865      4
866     18
867      3
868     10
869      9
870      3
871      3
872      3
873      4
874      7
875      6
876      5
877      4
878      4
879      4
880      8
881      4
882      5
883      7
884      9
885      5
886      8
887     18
888      4
889      4
890      4
891      4
892      3
893      5
894      4
895      3
896      3
897      5
898      5
899      3
900      2
901      3
902      5
903      4
904      4
905     16
906      3
907      4
908      4
909      4
910      5
911      6
912      4
913      3
914      5
915      5
916     16
917     12
918      4
919      5
920      5
921      8
922      5
923      7
924      7
925      6
926      7
927      7
928      3
929      5
930      5
931      4
932      5
933     12
934      3
935      4
936      4
937      9
938      9
939      7
940      4
941      4
942      5
943      9
944      4
945      4
946      2
947      4
948      4
949      4
950      9
951      6
952      9
953      3
954      4
955      5
956      4
957      4
958      6
959      5
960      3
961      6
962      3
963      4
964      4
965      4
966      3
967      5
968      4
969     12
970      6
971      4
972      3
973      6
974      4
975      3
976      3
977      6
978      4
979      7
980      4
981      5
982      4
983     12
984      8
985      4
986      5
987      4
988      6
989      4
990      5
991      8
992      4
993     13
994      5
995      4
996      4
997      6
998      4
999      4
1000     5
1001     6
1002     4
1003     8
1004     8
1005     2
1006     8
1007     6
1008     2
1009     4
1010     9
1011     7
1012     4
1013     3
1014    17
1015     6
1016     9
1017     4
1018     4
1019    12
1020     2
1021    11
1022     9
1023     4
1024     5
1025     6
1026     9
1027     4
1028     4
1029     4
1030     9
1031     3
1032     3
1033     6
1034     4
1035     5
1036     4
1037     3
1038     3
1039     4
1040     2
1041     3
1042     3
1043     3
Name: bathroom, dtype: int64

In [63]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),1,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),2,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),1,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [64]:
df.shape

(964, 19)

#Balcony

In [65]:
df['balcony'].value_counts()

3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: balcony, dtype: int64

In [69]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No', '0')

In [70]:
df['balcony']

0       3+
1        2
2       3+
3       3+
4       3+
5       3+
6       3+
7       3+
8        1
9       3+
10      3+
11      3+
12      3+
13      3+
14      3+
15       3
16      3+
17      3+
18      3+
19       3
20       3
21      3+
22       3
23       2
24       3
25      3+
26       1
27      3+
28      3+
29       3
30      3+
31       3
32       3
33      3+
34       2
35       2
36      3+
37       2
38      3+
39       3
40      3+
41       1
42      3+
43      3+
44      3+
45      3+
46       3
47      3+
48      3+
49       2
50       2
51      3+
52      3+
53       3
54       3
55       2
56      3+
57      3+
58      3+
59      3+
60      3+
61       2
64       1
65      3+
79      3+
80       2
90      3+
91      3+
101     3+
106      2
107      2
108      2
109      3
112     3+
113      1
114      2
116     3+
117      2
118     3+
119      3
120     3+
121      2
122      3
123      2
124      2
125      2
126      2
127     3+
128      2
129      3
130      3
131      3
132      2
133      2
134     3+
135      2
136      2
137     3+
138     3+
139     3+
140     3+
141     3+
142      3
143      1
144      2
145      1
146      1
147      1
148      2
149      2
150      3
151     3+
152     3+
153     3+
154     3+
155      2
156      3
157      0
158      2
159      1
160      2
161     3+
162     3+
163     3+
164     3+
165     3+
166      1
167      1
168      1
169      2
170     3+
171      0
172      1
173     3+
174     3+
175     3+
176      3
177     3+
178      0
179      3
180     3+
181      3
182      2
183      1
184      0
185      0
186      3
187      1
188      2
189      2
190      2
191      0
192     3+
193      3
194      0
195      1
196      0
197      2
198      0
199      3
200      2
201      0
202     3+
203     3+
204      3
205     3+
206      0
207     3+
208      2
209      2
210      0
211      2
212      2
213      1
214      3
215     3+
216     3+
217      0
218      1
219     3+
220      2
221      2
222      2
223      2
224      2
225      2
226      1
227      2
228      2
229      2
230      1
231     3+
232      1
233      0
234      0
235     3+
236     3+
237      0
238      2
239      0
240      0
241      2
242      0
243      1
244      0
245     3+
246      1
247      2
248      0
249      3
250      2
251      3
252      2
253      1
254      2
255      0
256      0
257      0
258     3+
259      2
262      1
263      0
264      1
265      0
266      2
267      2
268     3+
269     3+
270     3+
271      2
272      1
274      2
275      2
276      2
279      2
280      2
281      2
282     3+
283     3+
285     3+
286      2
287      0
288      0
289     3+
297      3
298      1
299      1
300     3+
301      0
302      1
303      1
304     3+
305      0
306      1
307      1
308     3+
309      0
310      0
311      2
312      0
313     3+
314      0
315      0
316      0
317      0
322      0
323     3+
327      2
328      1
329      0
330      1
331     3+
332      1
333      2
334      0
335      2
336      1
337      2
338      0
339      0
340      1
341      0
342      2
343      0
344      1
345      0
346      0
347      3
348      0
349     3+
350      0
351      2
352      2
353     3+
354      0
356      2
357     3+
358      2
359      0
360      2
361      1
362      0
363     3+
364      1
365      2
366      2
367     3+
368      0
369      0
370      1
371      0
372      0
373      3
374      1
375     3+
376      2
377      0
378      1
379      1
380      3
381     3+
382      3
383      2
385      2
386     3+
387     3+
388      1
389      2
390      1
391     3+
392      1
393     3+
394      2
395     3+
396      3
397      0
398     3+
399      2
400      3
401      0
402      3
403      3
404      1
405      1
406      0
407      0
408      1
409      1
410     3+
411      0
412      1
413     3+
414      2
415      2
416      1
417      2
418     3+
419      1
420      1
421     3+
422      2
423      0
424      1
425      2
426     3+
427      3
428     3+
429      3
430      2
431     3+
432     3+
433      3
434      1
435      1
436      2
437      1
438      1
439      2
440      0
441      1
442     3+
443      1
444     3+
445      0
446      3
448      1
449      1
450     3+
451      3
452      1
453      1
454     3+
455      2
456     3+
457      3
458      3
459      1
460      2
461      1
462      2
463      2
464      2
465     3+
466     3+
467      3
468      1
469     3+
470      2
471      3
472      3
473      1
474      1
475     3+
476      1
477      0
478      2
479      3
480      2
481      1
482      2
483      0
484      1
485      2
486     3+
487      0
488      1
489      0
490      2
491      0
492      0
493      3
494      0
495      2
496      0
497     3+
498      0
499      0
500     3+
501      2
502      0
503      1
504      1
505      1
506     3+
507      3
508      3
509      2
510     3+
511      2
512     3+
513      0
514      2
515      2
516      0
517      0
518     3+
519      0
520      0
521      2
523     3+
524      3
525      2
526      1
527      2
528      2
529      3
530     3+
531      0
532      2
533     3+
534     3+
535      0
536      0
537      0
538      0
539      3
540      0
541      0
542      2
543      0
544      3
545      1
546      0
547     3+
549      1
550     3+
551      0
552      2
553      3
554      0
555      0
556      0
557      0
558      2
559      0
560      0
561      1
562      0
563      0
564      0
565      2
566      1
567      3
568      0
569      2
570      0
571      0
572     3+
573      0
574      3
575      2
576      0
577      2
578     3+
579      1
580     3+
581     3+
582      3
583      0
584     3+
585     3+
586      2
587      3
588      1
589     3+
590      3
591      0
592      2
593      0
594      2
595      0
596      0
597      3
598      1
599      2
600     3+
601      0
602     3+
603      1
604      2
605     3+
606      3
607      1
608      2
609     3+
610      2
611     3+
612      2
613      1
614      0
615      3
616      2
617      3
618      1
619     3+
620      1
622      0
623      2
624      2
625      3
626     3+
627     3+
628      3
629      2
630     3+
631      0
632      2
633     3+
634      1
635      1
636      1
637     3+
638      2
639     3+
640      1
641      1
642      1
643      2
644      2
645      2
646     3+
647     3+
648     3+
649     3+
650     3+
651     3+
652     3+
653      2
654     3+
655      2
656      3
657     3+
658     3+
659     3+
660      3
661     3+
662     3+
663     3+
664     3+
665     3+
666     3+
667      3
668     3+
669     3+
670     3+
671     3+
672     3+
673      3
674     3+
675     3+
676      2
677      3
678     3+
679     3+
680      2
681      2
682      2
683     3+
684      3
685      2
686      3
687      2
688      2
689      1
690     3+
691      2
692      3
693     3+
694     3+
695     3+
696     3+
697     3+
698      3
699     3+
700      3
701     3+
702     3+
703     3+
704     3+
705      2
706      3
707      2
708      2
709      2
710      1
711     3+
712     3+
713     3+
714     3+
715      3
716      3
717      2
718      3
719      3
720      3
721     3+
722      0
723     3+
724     3+
725      3
726      3
727     3+
728     3+
729      3
730     3+
731     3+
732     3+
733     3+
734      1
735      1
736     3+
737     3+
738     3+
739     3+
740      3
741      2
742     3+
743     3+
744      2
745     3+
746      2
747      3
748     3+
749     3+
750      2
751     3+
752      3
753      2
754     3+
755     3+
756     3+
757      2
758      3
759      2
760     3+
761     3+
762      2
763     3+
764      3
765     3+
766     3+
767     3+
768     3+
769     3+
770      3
771      2
772     3+
785     3+
786      2
787     3+
788      3
789      2
790     3+
791      3
792      3
793      3
794      3
795     3+
796     3+
797      3
798      2
799      3
800      3
801      3
802     3+
803     3+
804      3
805     3+
806     3+
807      2
808      1
809     3+
810      3
811     3+
812     3+
813      3
814     3+
815      2
816      3
817     3+
818     3+
819      3
820     3+
821     3+
822      3
823     3+
825      3
826     3+
827     3+
828     3+
829     3+
830      3
831     3+
832      3
833      3
834      2
835     3+
836     3+
837     3+
838     3+
839      3
840      3
841     3+
842     3+
843      2
844     3+
845      3
846      2
848      2
849      2
850     3+
851      3
852     3+
853      3
854      3
855      2
856      2
857      2
858     3+
859      3
860      2
861     3+
862     3+
863      3
864      2
865      2
866      2
867      2
868     3+
869     3+
870      3
871      2
872      3
873     3+
874     3+
875     3+
876     3+
877     3+
878     3+
879     3+
880      2
881      3
882     3+
883     3+
884     3+
885     3+
886     3+
887     3+
888     3+
889     3+
890      3
891     3+
892      2
893      2
894      3
895     3+
896     3+
897      2
898     3+
899     3+
900     3+
901     3+
902     3+
903     3+
904     3+
905     3+
906      3
907     3+
908      2
909      3
910     3+
911     3+
912     3+
913      3
914     3+
915     3+
916     3+
917     3+
918     3+
919     3+
920     3+
921     3+
922     3+
923     3+
924     3+
925     3+
926      3
927      3
928      3
929      3
930      2
931      2
932      2
933     3+
934      2
935      2
936      2
937     3+
938     3+
939     3+
940     3+
941     3+
942     3+
943     3+
944      3
945      3
946      3
947      2
948      2
949      3
950     3+
951     3+
952     3+
953      2
954     3+
955     3+
956     3+
957     3+
958     3+
959     3+
960      1
961     3+
962      2
963      2
964      2
965     3+
966      2
967      2
968      3
969     3+
970     3+
971      2
972      2
973     3+
974      2
975     3+
976      2
977      2
978      3
979      3
980      2
981     3+
982      2
983     3+
984      3
985      2
986      2
987     3+
988     3+
989      3
990     3+
991     3+
992      2
993     3+
994      2
995     3+
996     3+
997     3+
998     3+
999     3+
1000    3+
1001    3+
1002     3
1003    3+
1004    3+
1005     0
1006     3
1007    3+
1008     3
1009     3
1010    3+
1011    3+
1012     3
1013     3
1014    3+
1015     3
1016    3+
1017     3
1018     3
1019    3+
1020     2
1021    3+
1022    3+
1023    3+
1024     3
1025    3+
1026    3+
1027     3
1028    3+
1029     2
1030    3+
1031     2
1032     3
1033    3+
1034    3+
1035    3+
1036    3+
1037     3
1038     2
1039     3
1040     3
1041     2
1042     3
1043     2
Name: balcony, dtype: object

In [71]:
df.head(2)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN

#Additional room

In [73]:
df['additionalRoom'].value_counts()

Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Pooja Room,Servant Room,Store Room                7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: additionalRoom, dtype: int64

In [74]:
df['additionalRoom'].isnull().sum()

386

# Observation:-
- 386 null values present are there
- so what we can do replace null values with not available

In [75]:
df['additionalRoom'].fillna('not available', inplace =True)

In [76]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [78]:
df['additionalRoom'].isnull().sum()

0

#Floors

In [81]:
df['noOfFloor'].value_counts()

3 Floors     304
2 Floors     288
1 Floors     181
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: noOfFloor, dtype: int64

In [82]:
df['noOfFloor'].isnull().sum()

19

#Observation:-
- 19 null values present over there

In [86]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [87]:
df['noOfFloor'].shape

(964,)

#### we will handle 19 null values later on

In [88]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [90]:
df.head(1)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

#Facing

In [91]:
df['facing'].isnull().sum()

303

In [92]:
df['facing'].value_counts()

East          178
North-East    158
North         109
West           75
North-West     44
South-East     39
South          34
South-West     24
Name: facing, dtype: int64

In [93]:
df['facing'].fillna('NA',inplace=True)

In [94]:
df['facing'].isnull().sum()

0

- null values are filled

# Area

In [96]:
df['area'].value_counts()

(301 sq.m.) Plot Area        43
(84 sq.m.) Plot Area         37
(251 sq.m.) Plot Area        31
(167 sq.m.) Plot Area        25
(420 sq.m.) Plot Area        24
(226 sq.m.) Plot Area        21
(418 sq.m.) Plot Area        20
(125 sq.m.) Plot Area        19
(201 sq.m.) Plot Area        18
(50 sq.m.) Plot Area         16
(180 sq.m.) Plot Area        16
(135 sq.m.) Plot Area        15
(209 sq.m.) Plot Area        14
(171 sq.m.) Plot Area        12
(293 sq.m.) Plot Area        11
(334 sq.m.) Plot Area        11
(33 sq.m.) Plot Area         11
(42 sq.m.) Plot Area         11
(264 sq.m.) Plot Area        10
(220 sq.m.) Plot Area        10
(51 sq.m.) Plot Area          9
(145 sq.m.) Plot Area         8
(502 sq.m.) Plot Area         8
(151 sq.m.) Plot Area         8
(136 sq.m.) Plot Area         7
(134 sq.m.) Plot Area         7
(161 sq.m.) Plot Area         7
(100 sq.m.) Plot Area         6
(242 sq.m.) Plot Area         6
(5 sq.m.) Plot Area           6
(836 sq.m.) Plot Area         6
(52 sq.m.) Plot Area          6
(56 sq.m.) Plot Area          5
(93 sq.m.) Plot Area          5
(350 sq.m.) Plot Area         5
(84 sq.m.) Carpet Area        5
(579 sq.m.) Plot Area         5
(42 sq.m.) Built-up Area      5
(286 sq.m.) Plot Area         5
(435 sq.m.) Plot Area         5
(6 sq.m.) Plot Area           5
(372 sq.m.) Plot Area         5
(297 sq.m.) Plot Area         4
(93 sq.m.) Built-up Area      4
(650 sq.m.) Built-up Area     4
(253 sq.m.) Plot Area         4
(241 sq.m.) Plot Area         4
(7 sq.m.) Plot Area           4
(54 sq.m.) Plot Area          4
(109 sq.m.) Plot Area         4
(217 sq.m.) Plot Area         4
(418 sq.m.) Built-up Area     4
(279 sq.m.) Built-up Area     4
(91 sq.m.) Plot Area          3
(142 sq.m.) Plot Area         3
(22 sq.m.) Plot Area          3
(158 sq.m.) Plot Area         3
(63 sq.m.) Plot Area          3
(336 sq.m.) Plot Area         3
(84 sq.m.) Built-up Area      3
(139 sq.m.) Plot Area         3
(28 sq.m.) Plot Area          3
(144 sq.m.) Plot Area         3
(102 sq.m.) Built-up Area     3
(100 sq.m.) Built-up Area     3
(37 sq.m.) Plot Area          3
(14 sq.m.) Plot Area          3
(125 sq.m.) Built-up Area     3
(105 sq.m.) Plot Area         3
(9 sq.m.) Plot Area           3
(230 sq.m.) Plot Area         3
(223 sq.m.) Plot Area         3
(99 sq.m.) Plot Area          3
(98 sq.m.) Plot Area          3
(460 sq.m.) Plot Area         3
(67 sq.m.) Plot Area          3
(107 sq.m.) Plot Area         3
(557 sq.m.) Built-up Area     3
(268 sq.m.) Plot Area         3
(140 sq.m.) Plot Area         3
(681 sq.m.) Built-up Area     2
(33 sq.m.) Built-up Area      2
(232 sq.m.) Carpet Area       2
(132 sq.m.) Built-up Area     2
(85 sq.m.) Plot Area          2
(301 sq.m.) Built-up Area     2
(59 sq.m.) Plot Area          2
(15 sq.m.) Built-up Area      2
(146 sq.m.) Plot Area         2
(45 sq.m.) Built-up Area      2
(184 sq.m.) Plot Area         2
(115 sq.m.) Plot Area         2
(232 sq.m.) Plot Area         2
(105 sq.m.) Built-up Area     2
(73 sq.m.) Plot Area          2
(75 sq.m.) Carpet Area        2
(25 sq.m.) Plot Area          2
(219 sq.m.) Built-up Area     2
(34 sq.m.) Plot Area          2
(316 sq.m.) Plot Area         2
(89 sq.m.) Built-up Area      2
(113 sq.m.) Plot Area         2
(46 sq.m.) Plot Area          2
(521 sq.m.) Plot Area         2
(135 sq.m.) Carpet Area       2
(110 sq.m.) Carpet Area       2
(108 sq.m.) Plot Area         2
(376 sq.m.) Plot Area         2
(321 sq.m.) Plot Area         2
(222 sq.m.) Plot Area         2
(299 sq.m.) Plot Area         2
(650 sq.m.) Plot Area         2
(244 sq.m.) Plot Area         2
(318 sq.m.) Plot Area         2
(186 sq.m.) Built-up Area     2
(44 sq.m.) Plot Area          2
(209 sq.m.) Built-up Area     2
(70 sq.m.) Built-up Area      2
(46 sq.m.) Built-up Area      2
(372 sq.m.) Built-up Area     2
(83 sq.m.) Plot Area          2
(167 sq.m.) Built-up Area     2
(251 sq.m.) Built-up Area     2
(111 sq.m.) Built-up Area     2
(149 sq.m.) Built-up Area     2
(15 sq.m.) Plot Area          2
(121 sq.m.) Plot Area         2
(5 sq.m.) Built-up Area       2
(139 sq.m.) Built-up Area     2
(89 sq.m.) Plot Area          2
(88 sq.m.) Plot Area          2
(301 sq.m.) Carpet Area       2
(76 sq.m.) Built-up Area      2
(166 sq.m.) Plot Area         2
(41 sq.m.) Plot Area          2
(46 sq.m.) Carpet Area        2
(121 sq.m.) Built-up Area     2
(43 sq.m.) Plot Area          2
(21 sq.m.) Plot Area          1
(260 sq.m.) Carpet Area       1
(222 sq.m.) Built-up Area     1
(130 sq.m.) Plot Area         1
(111 sq.m.) Plot Area         1
(60 sq.m.) Plot Area          1
(339 sq.m.) Plot Area         1
(71 sq.m.) Built-up Area      1
(249 sq.m.) Built-up Area     1
(196 sq.m.) Plot Area         1
(1003 sq.m.) Plot Area        1
(590 sq.m.) Built-up Area     1
(153 sq.m.) Built-up Area     1
(4 sq.m.) Plot Area           1
(465 sq.m.) Built-up Area     1
(75 sq.m.) Built-up Area      1
(213 sq.m.) Plot Area         1
(401 sq.m.) Plot Area         1
(261 sq.m.) Plot Area         1
(471 sq.m.) Plot Area         1
(809371 sq.m.) Plot Area      1
(594 sq.m.) Built-up Area     1
(186 sq.m.) Carpet Area       1
(96 sq.m.) Carpet Area        1
(44 sq.m.) Carpet Area        1
(100 sq.m.) Carpet Area       1
(339 sq.m.) Built-up Area     1
(437 sq.m.) Built-up Area     1
(162 sq.m.) Built-up Area     1
(248 sq.m.) Built-up Area     1
(107 sq.m.) Carpet Area       1
(63 sq.m.) Built-up Area      1
(104 sq.m.) Built-up Area     1
(102 sq.m.) Carpet Area       1
(281 sq.m.) Plot Area         1
(201 sq.m.) Built-up Area     1
(585 sq.m.) Plot Area         1
(152 sq.m.) Plot Area         1
(353 sq.m.) Built-up Area     1
(66 sq.m.) Plot Area          1
(80 sq.m.) Plot Area          1
(300 sq.m.) Plot Area         1
(79 sq.m.) Plot Area          1
(176 sq.m.) Built-up Area     1
(210 sq.m.) Plot Area         1
(92 sq.m.) Carpet Area        1
(143 sq.m.) Built-up Area     1
(69 sq.m.) Plot Area          1
(73 sq.m.) Carpet Area        1
(354 sq.m.) Plot Area         1
(2592 sq.m.) Plot Area        1
(112 sq.m.) Built-up Area     1
(176 sq.m.) Plot Area         1
(128 sq.m.) Plot Area         1
(181 sq.m.) Plot Area         1
(509 sq.m.) Plot Area         1
(511 sq.m.) Built-up Area     1
(159 sq.m.) Plot Area         1
(234 sq.m.) Plot Area         1
(537 sq.m.) Plot Area         1
(13 sq.m.) Plot Area          1
(64 sq.m.) Plot Area          1
(754 sq.m.) Plot Area         1
(94 sq.m.) Built-up Area      1
(26 sq.m.) Plot Area          1
(180 sq.m.) Built-up Area     1
(189 sq.m.) Plot Area         1
(466 sq.m.) Built-up Area     1
(288 sq.m.) Plot Area         1
(314 sq.m.) Plot Area         1
(194 sq.m.) Built-up Area     1
(136 sq.m.) Built-up Area     1
(194 sq.m.) Plot Area         1
(443 sq.m.) Plot Area         1
(12 sq.m.) Plot Area          1
(179 sq.m.) Plot Area         1
(168 sq.m.) Plot Area         1
(302 sq.m.) Plot Area         1
(450 sq.m.) Plot Area         1
(250 sq.m.) Plot Area         1
(4699 sq.m.) Plot Area        1
(186 sq.m.) Plot Area         1
(138 sq.m.) Built-up Area     1
(23 sq.m.) Plot Area          1
(1049 sq.m.) Plot Area        1
(283 sq.m.) Plot Area         1
(319 sq.m.) Plot Area         1
(10 sq.m.) Built-up Area      1
(422 sq.m.) Plot Area         1
(8 sq.m.) Plot Area           1
(543 sq.m.) Plot Area         1
(305 sq.m.) Plot Area         1
(55 sq.m.) Plot Area          1
(595 sq.m.) Built-up Area     1
(393 sq.m.) Plot Area         1
(190 sq.m.) Plot Area         1
(16 sq.m.) Plot Area          1
(102 sq.m.) Plot Area         1
(308 sq.m.) Plot Area         1
(360 sq.m.) Plot Area         1
(669 sq.m.) Plot Area         1
(225 sq.m.) Plot Area         1
(510 sq.m.) Plot Area         1
(155 sq.m.) Plot Area         1
(207 sq.m.) Carpet Area       1
(195 sq.m.) Carpet Area       1
(302 sq.m.) Carpet Area       1
(20 sq.m.) Built-up Area      1
(478 sq.m.) Built-up Area     1
(57 sq.m.) Plot Area          1
(132 sq.m.) Plot Area         1
(71 sq.m.) Plot Area          1
(167 sq.m.) Carpet Area       1
(133 sq.m.) Plot Area         1
(95 sq.m.) Plot Area          1
(815 sq.m.) Plot Area         1
(158 sq.m.) Built-up Area     1
(340 sq.m.) Built-up Area     1
(44 sq.m.) Built-up Area      1
(28 sq.m.) Carpet Area        1
(111 sq.m.) Carpet Area       1
(325 sq.m.) Built-up Area     1
(24 sq.m.) Plot Area          1
(56 sq.m.) Built-up Area      1
(12 sq.m.) Built-up Area      1
(743 sq.m.) Plot Area         1
(220 sq.m.) Built-up Area     1
(25 sq.m.) Built-up Area      1
(223 sq.m.) Built-up Area     1
(56 sq.m.) Carpet Area        1
(200 sq.m.) Built-up Area     1
(251 sq.m.) Carpet Area       1
(278 sq.m.) Built-up Area     1
(233 sq.m.) Built-up Area     1
(13 sq.m.) Built-up Area      1
(254 sq.m.) Plot Area         1
(19 sq.m.) Plot Area          1
(160 sq.m.) Plot Area         1
(367 sq.m.) Built-up Area     1
(92 sq.m.) Plot Area          1
(121 sq.m.) Carpet Area       1
(465 sq.m.) Plot Area         1
(326 sq.m.) Plot Area         1
(31 sq.m.) Built-up Area      1
(452 sq.m.) Built-up Area     1
(385 sq.m.) Plot Area         1
(92 sq.m.) Built-up Area      1
(206 sq.m.) Plot Area         1
(177 sq.m.) Plot Area         1
(134 sq.m.) Carpet Area       1
(74 sq.m.) Built-up Area      1
(557 sq.m.) Plot Area         1
(87 sq.m.) Built-up Area      1
(144 sq.m.) Built-up Area     1
(325 sq.m.) Plot Area         1
(9 sq.m.) Built-up Area       1
(51 sq.m.) Built-up Area      1
(929 sq.m.) Carpet Area       1
(153 sq.m.) Plot Area         1
(18 sq.m.) Plot Area          1
(325 sq.m.) Carpet Area       1
(23 sq.m.) Carpet Area        1
(234 sq.m.) Carpet Area       1
(65 sq.m.) Plot Area          1
(117 sq.m.) Plot Area         1
(390 sq.m.) Plot Area         1
(74 sq.m.) Plot Area          1
(174 sq.m.) Plot Area         1
(6062 sq.m.) Carpet Area      1
(49 sq.m.) Carpet Area        1
(52 sq.m.) Built-up Area      1
(188 sq.m.) Built-up Area     1
(5 sq.m.) Carpet Area         1
(117 sq.m.) Built-up Area     1
(316 sq.m.) Built-up Area     1
(255 sq.m.) Plot Area         1
(98 sq.m.) Built-up Area      1
(135 sq.m.) Built-up Area     1
(70 sq.m.) Plot Area          1
(242 sq.m.) Built-up Area     1
(291 sq.m.) Carpet Area       1
(207 sq.m.) Built-up Area     1
(124 sq.m.) Built-up Area     1
(1254 sq.m.) Plot Area        1
(204 sq.m.) Plot Area         1
(90 sq.m.) Plot Area          1
(58 sq.m.) Plot Area          1
(1115 sq.m.) Plot Area        1
(291 sq.m.) Plot Area         1
(40 sq.m.) Plot Area          1
(246 sq.m.) Plot Area         1
(743 sq.m.) Built-up Area     1
(47 sq.m.) Plot Area          1
(7692 sq.m.) Plot Area        1
(124 sq.m.) Plot Area         1
(431 sq.m.) Plot Area         1
(93 sq.m.) Carpet Area        1
(22 sq.m.) Built-up Area      1
(18 sq.m.) Built-up Area      1
(50 sq.m.) Carpet Area        1
(163 sq.m.) Built-up Area     1
(32 sq.m.) Built-up Area      1
(49 sq.m.) Plot Area          1
(40 sq.m.) Carpet Area        1
(483 sq.m.) Built-up Area     1
(20064 sq.m.) Plot Area       1
(328 sq.m.) Built-up Area     1
(593 sq.m.) Built-up Area     1
(560 sq.m.) Plot Area         1
(110 sq.m.) Plot Area         1
(151 sq.m.) Carpet Area       1
(76 sq.m.) Plot Area          1
(2415 sq.m.) Plot Area        1
(149 sq.m.) Plot Area         1
Name: area, dtype: int64

In [99]:
# df['price']*10000000/
df['price_per_sqft']

0        20115.0
1       105751.0
2        38251.0
3        43066.0
4        53763.0
5        39062.0
6        37037.0
7        48889.0
8        38150.0
9        10077.0
10       32963.0
11       27778.0
12       34083.0
13       33200.0
14       30556.0
15       14914.0
16       29861.0
17       23333.0
18       41762.0
19       15451.0
20       12938.0
21       38095.0
22       25926.0
23       26235.0
24       38760.0
25       25926.0
26        9374.0
27       13410.0
28       21124.0
29       32593.0
30       24170.0
31       37037.0
32       28490.0
33      122222.0
34       13542.0
35       19097.0
36       48148.0
37       22222.0
38       22222.0
39       33333.0
40       32222.0
41        7290.0
42       27741.0
43       50000.0
44       43534.0
45       45889.0
46       34722.0
47           NaN
48       20690.0
49       29716.0
50       16378.0
51       17284.0
52       37777.0
53       12519.0
54       25562.0
55       27971.0
56       21000.0
57       24500.0
58        7058.0
59        7058.0
60       11250.0
61       23333.0
64       20000.0
65       35400.0
79       40135.0
80       16244.0
90       21605.0
91       10463.0
101      41615.0
106      14444.0
107      10101.0
108      38703.0
109      22222.0
112      23148.0
113       8557.0
114      16428.0
116      10556.0
117      13519.0
118      42032.0
119      24069.0
120      21605.0
121      13889.0
122      14650.0
123      13889.0
124      13778.0
125      15625.0
126      23333.0
127      21250.0
128      38667.0
129      26667.0
130      12593.0
131      26389.0
132      12963.0
133      25514.0
134      24845.0
135      17650.0
136      24280.0
137      26423.0
138       6666.0
139       8916.0
140      36667.0
141       9000.0
142      20000.0
143       9028.0
144       4074.0
145        630.0
146      86567.0
147      92857.0
148     100000.0
149      88157.0
150      29974.0
151      24691.0
152       2778.0
153      46906.0
154      25000.0
155      23699.0
156      25960.0
157      28424.0
158      33333.0
159       4490.0
160      14729.0
161      25111.0
162      25000.0
163       7309.0
164      10556.0
165      74074.0
166      12000.0
167      10233.0
168      26852.0
169       8878.0
170      14286.0
171       8928.0
172       8007.0
173      11111.0
174       5698.0
175      28283.0
176      24214.0
177      26613.0
178     138888.0
179      10000.0
180       7666.0
181       7407.0
182       8333.0
183       4666.0
184      13333.0
185      60000.0
186      11111.0
187       7778.0
188      40775.0
189      99173.0
190      12222.0
191       6172.0
192      22222.0
193       9111.0
194      80357.0
195       4117.0
196       7308.0
197       8701.0
198       8000.0
199      25926.0
200       6666.0
201       2296.0
202       8888.0
203      33333.0
204      12444.0
205       9793.0
206       6250.0
207       8486.0
208      11717.0
209       7589.0
210      13333.0
211      12592.0
212      15384.0
213       7843.0
214      22222.0
215      23333.0
216      29336.0
217      10288.0
218      11284.0
219      11029.0
220      10277.0
221       6944.0
222       8518.0
223      10555.0
224      11250.0
225        557.0
226       8888.0
227      11852.0
228       8947.0
229      39265.0
230       6083.0
231     230547.0
232       8411.0
233      32291.0
234      41666.0
235       8889.0
236       7280.0
237      90000.0
238      10089.0
239       8697.0
240       8500.0
241       9333.0
242       8235.0
243      13333.0
244      21667.0
245      20425.0
246       5472.0
247       6944.0
248      57692.0
249      60000.0
250          NaN
251       3857.0
252      21759.0
253       8333.0
254       7407.0
255      75000.0
256      10482.0
257      25386.0
258       8735.0
259       9444.0
262      20000.0
263      18667.0
264      18889.0
265       2525.0
266      24306.0
267      17695.0
268      21519.0
269      17817.0
270          2.0
271       6173.0
272      55000.0
274      13888.0
275      20323.0
276      20359.0
279       5833.0
280      11693.0
281      26667.0
282      53125.0
283      17900.0
285      39886.0
286     126865.0
287      40909.0
288      27155.0
289      14492.0
297      14167.0
298      11111.0
299          NaN
300      13157.0
301       5888.0
302      11111.0
303       7875.0
304       9654.0
305       4808.0
306       8222.0
307      11111.0
308       3857.0
309      50000.0
310      11273.0
311       8000.0
312       7627.0
313       5666.0
314       5000.0
315       5000.0
316       6567.0
317      22068.0
322       8386.0
323      12444.0
327      11111.0
328      28674.0
329       9725.0
330      21111.0
331       7500.0
332      10784.0
333      12162.0
334       8910.0
335      10518.0
336      19869.0
337       8796.0
338       9722.0
339       7522.0
340       5658.0
341       5000.0
342      24545.0
343       7701.0
344       8235.0
345      14072.0
346      26000.0
347      24305.0
348      19286.0
349      22634.0
350      26570.0
351      11111.0
352       6410.0
353     133079.0
354      15257.0
356       5778.0
357       6111.0
358      15625.0
359      78125.0
360      17955.0
361       7916.0
362     211111.0
363      80000.0
364      35000.0
365      10000.0
366     120000.0
367      22297.0
368     125000.0
369       8889.0
370      73333.0
371          NaN
372      11111.0
373      26235.0
374       6790.0
375      20833.0
376     315789.0
377      10224.0
378       3500.0
379       3285.0
380      74000.0
381      27139.0
382      10000.0
383       5555.0
385      23662.0
386      17574.0
387      13333.0
388      10753.0
389       9091.0
390      23557.0
391      59259.0
392     105263.0
393      21195.0
394        151.0
395      25103.0
396      13889.0
397      14954.0
398      23333.0
399       8784.0
400       6500.0
401      35494.0
402      11464.0
403      11718.0
404      11555.0
405      50000.0
406       3874.0
407       7576.0
408      11556.0
409      10753.0
410      20635.0
411      10378.0
412      11888.0
413      17284.0
414      32258.0
415      11111.0
416      12222.0
417      16389.0
418      31506.0
419       9722.0
420      12820.0
421     229885.0
422      10000.0
423       8889.0
424      12400.0
425       9259.0
426        232.0
427      15257.0
428     218750.0
429      54794.0
430      14245.0
431       6367.0
432      37313.0
433      90909.0
434       9444.0
435       5000.0
436          NaN
437      10122.0
438      10000.0
439       8642.0
440       6481.0
441       6707.0
442     245398.0
443       9259.0
444          NaN
445      11904.0
446       9135.0
448       7111.0
449       8012.0
450     183333.0
451      12500.0
452      10142.0
453       8444.0
454       8125.0
455      14583.0
456      17037.0
457      11538.0
458       8730.0
459      12222.0
460      14444.0
461      11574.0
462          NaN
463      26667.0
464      11111.0
465       8230.0
466      13095.0
467      30556.0
468      11852.0
469      10000.0
470      29311.0
471      11250.0
472      30384.0
473       8444.0
474      19818.0
475       1992.0
476       7619.0
477      98214.0
478      13499.0
479       7820.0
480       5555.0
481       4000.0
482      14720.0
483       5664.0
484      19753.0
485      76000.0
486      37037.0
487      63492.0
488       9000.0
489       4444.0
490       2500.0
491       6667.0
492       3704.0
493      12777.0
494       6648.0
495      11407.0
496      20233.0
497      17778.0
498      20062.0
499      11494.0
500      25543.0
501      12343.0
502      16892.0
503       8000.0
504      17500.0
505       3904.0
506      14323.0
507       4222.0
508     181818.0
509      75000.0
510      26620.0
511       5555.0
512      10000.0
513       9722.0
514       9500.0
515      17937.0
516       3254.0
517       5333.0
518      30556.0
519       4583.0
520      12500.0
521      21875.0
523      16667.0
524       7075.0
525       8078.0
526       4251.0
527      17584.0
528       5397.0
529       9074.0
530       5583.0
531       3519.0
532      11194.0
533     100000.0
534       6981.0
535       6702.0
536       9444.0
537      10556.0
538      18333.0
539       4877.0
540       7479.0
541       7400.0
542      16003.0
543       8000.0
544       9444.0
545       9103.0
546       7727.0
547      45710.0
549       8702.0
550       5950.0
551       3500.0
552       9722.0
553       8889.0
554      26973.0
555      32407.0
556      13750.0
557       6000.0
558      14890.0
559       9210.0
560       6800.0
561      10518.0
562       7333.0
563       8101.0
564       6944.0
565      14184.0
566       4260.0
567      10582.0
568       9390.0
569      84000.0
570       6938.0
571      15555.0
572      33333.0
573       7539.0
574      10000.0
575      10067.0
576       1649.0
577      10000.0
578      10000.0
579      13000.0
580      28898.0
581      28200.0
582       7168.0
583      20444.0
584          NaN
585      35185.0
586       6289.0
587      17857.0
588       7000.0
589      14166.0
590      30968.0
591       7777.0
592      18658.0
593      10484.0
594     160000.0
595       8127.0
596       5000.0
597       8000.0
598       7555.0
599      49500.0
600       8889.0
601      13030.0
602     308333.0
603       8333.0
604      10610.0
605      18889.0
606       7302.0
607       8155.0
608      10591.0
609      24074.0
610      14815.0
611       5160.0
612     144444.0
613       9615.0
614       9444.0
615      10101.0
616      22222.0
617      32407.0
618       6813.0
619      15046.0
620      11583.0
622       6034.0
623      10085.0
624      17778.0
625      40611.0
626      29630.0
627      29629.0
628      10740.0
629       4444.0
630      17980.0
631      55000.0
632      19737.0
633       5093.0
634      25463.0
635      12000.0
636       7007.0
637       8920.0
638      35294.0
639      12963.0
640       8254.0
641       5128.0
642       5777.0
643      15926.0
644      11111.0
645      14285.0
646      34307.0
647      51864.0
648      44265.0
649      29444.0
650      39074.0
651      38734.0
652      23442.0
653      41833.0
654      27778.0
655     600000.0
656      23889.0
657      25000.0
658      10260.0
659      31915.0
660      11102.0
661       8866.0
662      36911.0
663      36111.0
664      15444.0
665      11240.0
666      15437.0
667      14351.0
668      27191.0
669     241666.0
670      32963.0
671      33592.0
672      24455.0
673      26667.0
674      26389.0
675     194444.0
676      18444.0
677      11600.0
678      38095.0
679      13492.0
680      33951.0
681      11157.0
682       8444.0
683      21495.0
684      42054.0
685       1560.0
686      20741.0
687      13178.0
688      12000.0
689      26428.0
690      82540.0
691      18888.0
692      31481.0
693      13501.0
694      20988.0
695     400000.0
696      21296.0
697      34722.0
698      18626.0
699      24366.0
700      26298.0
701       7500.0
702      24171.0
703      23000.0
704      29697.0
705      33333.0
706      36111.0
707       6778.0
708      22812.0
709     261194.0
710     178571.0
711      27461.0
712      31686.0
713      22222.0
714      23061.0
715      32222.0
716      17662.0
717      39841.0
718      37627.0
719      23148.0
720      29880.0
721      20068.0
722      16569.0
723      21242.0
724      11574.0
725      32562.0
726      13000.0
727      22429.0
728      39530.0
729      22222.0
730      38889.0
731          NaN
732      57206.0
733      27222.0
734      63554.0
735      10601.0
736      20940.0
737      32253.0
738      37037.0
739          NaN
740      23704.0
741      23693.0
742      15989.0
743      19268.0
744      19360.0
745      45833.0
746      29880.0
747      23437.0
748       2716.0
749      39841.0
750      32222.0
751      40850.0
752      12342.0
753      15555.0
754      26111.0
755      31790.0
756      24691.0
757     235376.0
758      29293.0
759      16004.0
760      27333.0
761      17624.0
762      38580.0
763      27778.0
764      35556.0
765      38580.0
766      35000.0
767      30864.0
768          NaN
769     161849.0
770      27778.0
771      16056.0
772      17707.0
785       7718.0
786      25535.0
787       1859.0
788      17037.0
789      10579.0
790      42194.0
791      15625.0
792      15278.0
793     201388.0
794      17187.0
795          NaN
796      44444.0
797      18928.0
798      10926.0
799      19608.0
800       8089.0
801       6849.0
802      24691.0
803          NaN
804      19607.0
805      40000.0
806      34846.0
807      31444.0
808      26235.0
809      22222.0
810      23457.0
811      27083.0
812      43210.0
813      31926.0
814      38611.0
815      27911.0
816      29022.0
817      12837.0
818      12198.0
819      35741.0
820          NaN
821      16666.0
822      35556.0
823       9634.0
825      31481.0
826       7827.0
827      38760.0
828      23556.0
829      10035.0
830      28841.0
831      26615.0
832      24155.0
833      14815.0
834      22222.0
835      62222.0
836       6597.0
837       7870.0
838      26852.0
839      28233.0
840      15111.0
841      34722.0
842      19820.0
843       1087.0
844          NaN
845      31481.0
846      26235.0
848      36883.0
849      37037.0
850      27871.0
851      35109.0
852      17692.0
853      38022.0
854      33333.0
855      25309.0
856      16990.0
857      14222.0
858      22222.0
859      16388.0
860      22075.0
861      11666.0
862      47167.0
863       7937.0
864      20197.0
865      20635.0
866      34037.0
867      10123.0
868      28858.0
869      28549.0
870      15555.0
871      13513.0
872      20769.0
873      34568.0
874      21097.0
875      33951.0
876      24306.0
877      25556.0
878      36111.0
879       7756.0
880      21825.0
881      12342.0
882      16577.0
883      17706.0
884      29074.0
885      29880.0
886      42222.0
887      38194.0
888      21605.0
889      38194.0
890      37778.0
891      31111.0
892      17213.0
893      18620.0
894      17014.0
895       7750.0
896       7172.0
897      29638.0
898      33333.0
899       8137.0
900       7582.0
901      48148.0
902      18605.0
903      16066.0
904      55556.0
905      38986.0
906      24510.0
907      11428.0
908      22184.0
909      30247.0
910      20370.0
911      31666.0
912      18889.0
913     283333.0
914      31481.0
915      42222.0
916      59259.0
917      45833.0
918      18008.0
919      26235.0
920          NaN
921      33333.0
922      12285.0
923      19293.0
924      20599.0
925     173992.0
926      21367.0
927      20299.0
928      41818.0
929       9634.0
930      19231.0
931      20833.0
932      33333.0
933       6875.0
934      14667.0
935      14787.0
936      16319.0
937      18250.0
938      27390.0
939      30728.0
940      35000.0
941      30556.0
942      41315.0
943       3786.0
944      60000.0
945      24691.0
946       9349.0
947      23504.0
948      21605.0
949     234375.0
950      26235.0
951      21786.0
952      35000.0
953       8235.0
954      15432.0
955      37627.0
956      21251.0
957      30556.0
958      27160.0
959      35530.0
960      22046.0
961      22222.0
962      33333.0
963      27132.0
964      22855.0
965      40741.0
966      34722.0
967      29333.0
968      32328.0
969     290948.0
970      25562.0
971      12393.0
972      22331.0
973      20317.0
974      18088.0
975      21759.0
976      16600.0
977      21219.0
978      19125.0
979      18885.0
980      15000.0
981      37037.0
982      18814.0
983      32328.0
984      23457.0
985      16975.0
986      18889.0
987      14000.0
988      32407.0
989     266666.0
990      26502.0
991      23148.0
992      32407.0
993      33951.0
994      18808.0
995      31481.0
996      10838.0
997      19847.0
998      23148.0
999      12037.0
1000     17820.0
1001     24390.0
1002     35185.0
1003         NaN
1004     26063.0
1005     79365.0
1006     23932.0
1007     24573.0
1008     24005.0
1009     32870.0
1010     33404.0
1011     23240.0
1012     29630.0
1013     16071.0
1014     51440.0
1015     26667.0
1016     28782.0
1017     34491.0
1018     34351.0
1019     47803.0
1020      6230.0
1021     33665.0
1022     44444.0
1023         NaN
1024         NaN
1025     20566.0
1026     22222.0
1027     26667.0
1028     20349.0
1029     23148.0
1030     21124.0
1031     24202.0
1032     24155.0
1033     23870.0
1034     24500.0
1035     24845.0
1036     20026.0
1037     28787.0
1038     12551.0
1039     30556.0
1040     31481.0
1041     33333.0
1042     33129.0
1043     14815.0
Name: price_per_sqft, dtype: float64

In [105]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

#Observation:-
- NaN values are present

In [97]:
df['area'].isnull().sum()

0

In [100]:
df.insert(loc=1,column='property_type',value='house')

In [101]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),1,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),2,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),1,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [102]:
df.shape

(964, 20)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 964 entries, 0 to 1043
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             964 non-null    object
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int64
 8   bathroom         964 non-null    int64
 9   balcony          964 non-null    object
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(2), int64(2), object(16)
memory usage: 158.2+ KB

In [108]:
df.to_csv('house_cleaned.csv',index=False)

In [106]:
df['area']

0          2610.0
1           539.0
2           549.0
3          1161.0
4           558.0
5          1152.0
6          3240.0
7          4091.0
8          2844.0
9          1935.0
10         1350.0
11         3240.0
12         1467.0
13         4518.0
14         2700.0
15         1341.0
16         3600.0
17          900.0
18         1760.0
19         2880.0
20         2628.0
21         3150.0
22         3240.0
23         3240.0
24         1961.0
25         2700.0
26         5067.0
27         2610.0
28         2367.0
29         3240.0
30         2259.0
31         2700.0
32         3159.0
33          818.0
34         1440.0
35         1728.0
36         2700.0
37         3240.0
38         2700.0
39         2700.0
40         1800.0
41          754.0
42         2700.0
43         2700.0
44         2745.0
45         2700.0
46         1800.0
47            NaN
48         2610.0
49         1935.0
50         1557.0
51         3240.0
52         4500.0
53         6382.0
54         1467.0
55         2592.0
56         4000.0
57         1449.0
58         3542.0
59         3542.0
60         8000.0
61          900.0
64         2250.0
65         1836.0
79         2367.0
80         3078.0
90         2546.0
91         5400.0
101        2115.0
106        2250.0
107        4950.0
108        2700.0
109        8775.0
112        3240.0
113         783.0
114        3500.0
116        5400.0
117        2367.0
118        2736.0
119        3195.0
120        3240.0
121        1116.0
122        2628.0
123        1440.0
124        2250.0
125        1440.0
126        3000.0
127        4000.0
128        2250.0
129        4687.0
130        5400.0
131        3600.0
132        5400.0
133        2430.0
134        1449.0
135        1728.0
136        2430.0
137        2214.0
138        6001.0
139        6000.0
140        1800.0
141        7000.0
142        6000.0
143         720.0
144        1350.0
145       13492.0
146          67.0
147          70.0
148          61.0
149          76.0
150        1935.0
151        2430.0
152       22498.0
153        1503.0
154        1800.0
155        1557.0
156         963.0
157        1935.0
158        4500.0
159       15479.0
160        3870.0
161        4500.0
162        4500.0
163        5500.0
164        5400.0
165         135.0
166         550.0
167         684.0
168         540.0
169        1070.0
170        3150.0
171        1008.0
172         562.0
173         900.0
174        1053.0
175        2475.0
176        1623.0
177        1503.0
178          54.0
179         900.0
180        3587.0
181         675.0
182         600.0
183         900.0
184         450.0
185          80.0
186         450.0
187         450.0
188         981.0
189         242.0
190        1800.0
191        1782.0
192        3600.0
193         900.0
194         112.0
195        1700.0
196        1300.0
197        1494.0
198         450.0
199        1350.0
200        1200.0
201         653.0
202         900.0
203        1800.0
204        2250.0
205        2808.0
206        2800.0
207        3653.0
208         990.0
209        1120.0
210         675.0
211         270.0
212        3250.0
213         459.0
214        2250.0
215        4071.0
216        2471.0
217        1458.0
218        1152.0
219        3400.0
220         360.0
221        3240.0
222        1350.0
223         900.0
224         436.0
225       26032.0
226         900.0
227        1350.0
228         950.0
229        1783.0
230         822.0
231         347.0
232         535.0
233         192.0
234         240.0
235        4635.0
236        1305.0
237          50.0
238         446.0
239        2150.0
240        1000.0
241         450.0
242         510.0
243         900.0
244        3000.0
245        1836.0
246        4569.0
247        3240.0
248         130.0
249          50.0
250           NaN
251        3500.0
252        2160.0
253         720.0
254         297.0
255         220.0
256         477.0
257         906.0
258        1431.0
259        1800.0
262        3000.0
263        1500.0
264        1652.0
265         277.0
266        1440.0
267        1458.0
268        3950.0
269        2245.0
270     7250000.0
271         972.0
272         200.0
274        1800.0
275        1722.0
276        1449.0
279        1200.0
280         992.0
281        6000.0
282        1600.0
283        5000.0
285        3510.0
286          67.0
287         330.0
288        4861.0
289        4140.0
297         360.0
298         990.0
299           NaN
300        1900.0
301         900.0
302        1800.0
303         800.0
304        8287.0
305         936.0
306         450.0
307        1548.0
308        3500.0
309         100.0
310         550.0
311       10000.0
312        2360.0
313        3000.0
314        1100.0
315        3000.0
316        2360.0
317         145.0
322        2504.0
323        4500.0
327         585.0
328         558.0
329         802.0
330         450.0
331        5133.0
332         612.0
333         370.0
334         954.0
335        1426.0
336         765.0
337        1137.0
338        1080.0
339        1130.0
340        1025.0
341         900.0
342         550.0
343         909.0
344        1700.0
345        3660.0
346        2500.0
347        1440.0
348        7000.0
349        2518.0
350        1242.0
351        1575.0
352        1170.0
353         263.0
354         603.0
356         900.0
357        1800.0
358         480.0
359         160.0
360        2367.0
361         467.0
362         270.0
363         100.0
364         600.0
365        1100.0
366          50.0
367         538.0
368         360.0
369         900.0
370         150.0
371           NaN
372        2700.0
373        3240.0
374        1620.0
375         360.0
376         190.0
377         802.0
378        1000.0
379        3501.0
380         250.0
381        3132.0
382         900.0
383         900.0
385        2430.0
386        2646.0
387        5400.0
388         558.0
389        4950.0
390         552.0
391         540.0
392          57.0
393         920.0
394       82781.0
395        2430.0
396         360.0
397        1337.0
398         900.0
399        1423.0
400        1000.0
401        3240.0
402         785.0
403         640.0
404        1125.0
405          96.0
406        1755.0
407        1980.0
408        1125.0
409         558.0
410        3150.0
411         472.0
412         900.0
413        1215.0
414        1426.0
415         900.0
416         900.0
417        1800.0
418        1460.0
419         360.0
420        1170.0
421         435.0
422        5200.0
423         450.0
424         500.0
425         540.0
426      215517.0
427         603.0
428         160.0
429         146.0
430        1053.0
431        3534.0
432        3618.0
433          55.0
434        1800.0
435         900.0
436           NaN
437        1186.0
438        1800.0
439        1736.0
440         540.0
441         820.0
442         175.0
443         432.0
444           NaN
445        2520.0
446         471.0
448         450.0
449         587.0
450         300.0
451         600.0
452         700.0
453         450.0
454        4000.0
455         363.0
456        1350.0
457        1300.0
458        1260.0
459        1105.0
460         900.0
461        1080.0
462           NaN
463         540.0
464         450.0
465        1215.0
466        4200.0
467        1800.0
468         675.0
469         900.0
470        1467.0
471         800.0
472        1070.0
473         450.0
474        1872.0
475       65261.0
476         525.0
477          56.0
478         963.0
479         959.0
480         540.0
481         450.0
482        1053.0
483         565.0
484        2025.0
485          50.0
486        3240.0
487        1260.0
488         500.0
489        2700.0
490        1600.0
491        1500.0
492        1350.0
493         900.0
494        1053.0
495        2700.0
496        1458.0
497        4500.0
498        3240.0
499        2610.0
500        3132.0
501        2228.0
502        1332.0
503        1812.0
504        2000.0
505        2100.0
506        7331.0
507         900.0
508         550.0
509         100.0
510        1728.0
511         900.0
512        7000.0
513         360.0
514        1000.0
515         892.0
516         891.0
517         450.0
518        1833.0
519        1200.0
520        4000.0
521         823.0
523         900.0
524        1484.0
525        2228.0
526        1035.0
527         472.0
528        1297.0
529        1080.0
530        6000.0
531        1336.0
532        1072.0
533         900.0
534        4426.0
535        4700.0
536        1800.0
537        4500.0
538         900.0
539        1743.0
540        2674.0
541        1000.0
542        1156.0
543         500.0
544         900.0
545         758.0
546        1100.0
547        2844.0
549        1609.0
550        3025.0
551        2000.0
552         720.0
553        2700.0
554        1242.0
555        2160.0
556        1200.0
557        1000.0
558        1632.0
559        3800.0
560         500.0
561         713.0
562         750.0
563         864.0
564        9001.0
565         846.0
566        1150.0
567        1890.0
568         394.0
569          50.0
570        1081.0
571        2250.0
572        1350.0
573        1539.0
574         900.0
575         745.0
576         788.0
577         960.0
578        1350.0
579         500.0
580        3806.0
581        6390.0
582         921.0
583        2250.0
584           NaN
585         540.0
586        2385.0
587        1400.0
588        1000.0
589         600.0
590         646.0
591         900.0
592         477.0
593         763.0
594         100.0
595        1095.0
596        2680.0
597        2125.0
598         450.0
599        2000.0
600         450.0
601        1650.0
602          60.0
603         540.0
604         547.0
605         900.0
606         630.0
607         981.0
608         548.0
609        1080.0
610        1350.0
611        7500.0
612          45.0
613        2340.0
614         900.0
615        1980.0
616        4500.0
617        1080.0
618         807.0
619        4320.0
620        1200.0
622        1160.0
623         585.0
624        2250.0
625        3078.0
626         540.0
627         540.0
628        2700.0
629         900.0
630         945.0
631        1000.0
632        3420.0
633       10799.0
634        1080.0
635         225.0
636         999.0
637        1065.0
638        2295.0
639        5400.0
640         460.0
641        1170.0
642        1125.0
643        4521.0
644        1350.0
645        7000.0
646        4518.0
647        2844.0
648        4518.0
649        3240.0
650        2700.0
651        4466.0
652        1557.0
653        4518.0
654        3240.0
655         400.0
656         900.0
657         900.0
658        7271.0
659        2115.0
660         540.0
661        4500.0
662        1845.0
663        1800.0
664        4500.0
665        6228.0
666        2494.0
667        2230.0
668        3240.0
669          60.0
670        2700.0
671        1935.0
672        1836.0
673        8250.0
674        3600.0
675         360.0
676        2250.0
677        2500.0
678        3150.0
679        6300.0
680        3240.0
681        1210.0
682        2250.0
683        1512.0
684        4518.0
685       46795.0
686        2700.0
687        1935.0
688        2000.0
689        7000.0
690        3150.0
691         900.0
692         508.0
693        3222.0
694        3240.0
695         250.0
696        2160.0
697        3600.0
698        1557.0
699       11286.0
700        3042.0
701        3000.0
702        3438.0
703        2700.0
704        2475.0
705        1350.0
706        1800.0
707        2700.0
708        3222.0
709         402.0
710         154.0
711        2367.0
712        2367.0
713        3600.0
714        2385.0
715        1350.0
716        1557.0
717        4518.0
718        4518.0
719        1620.0
720        4518.0
721        2367.0
722        3078.0
723        1836.0
724        5400.0
725        3240.0
726        1546.0
727        1449.0
728        2340.0
729        2700.0
730        1350.0
731           NaN
732        4545.0
733        2160.0
734          83.0
735         443.0
736        5850.0
737        3240.0
738        3240.0
739           NaN
740        2700.0
741        1836.0
742        1845.0
743        1557.0
744         594.0
745        1800.0
746        4518.0
747        6400.0
748       20250.0
749        4518.0
750        1800.0
751        3060.0
752        2844.0
753        2250.0
754        3600.0
755        3240.0
756        2430.0
757         359.0
758        2475.0
759        2499.0
760        2250.0
761        2610.0
762        3240.0
763        3600.0
764        4500.0
765        3240.0
766        4571.0
767        3240.0
768           NaN
769         173.0
770        2430.0
771        1557.0
772        4518.0
785        3200.0
786        1449.0
787       98978.0
788        2700.0
789        3450.0
790        2844.0
791        2880.0
792        2880.0
793         360.0
794         576.0
795           NaN
796        4500.0
797        1400.0
798        2700.0
799        1836.0
800        1570.0
801        1095.0
802        2430.0
803           NaN
804        3315.0
805        4500.0
806        3240.0
807        2700.0
808        3240.0
809        2700.0
810        4050.0
811        7200.0
812        2430.0
813        1350.0
814        1800.0
815        3762.0
816        3618.0
817        4518.0
818        3771.0
819        3240.0
820           NaN
821        2400.0
822        4500.0
823        6228.0
825        2160.0
826        3194.0
827        1935.0
828        3600.0
829        6228.0
830        3762.0
831        1935.0
832        1449.0
833        2430.0
834        2700.0
835        2250.0
836        2425.0
837        2160.0
838        2700.0
839        5490.0
840        2250.0
841        3240.0
842        1665.0
843       50598.0
844           NaN
845        2700.0
846        3240.0
848        3240.0
849        3240.0
850        2332.0
851        4842.0
852        6500.0
853        2367.0
854        4500.0
855        3240.0
856        3243.0
857        2250.0
858        3600.0
859        1800.0
860        1268.0
861        4500.0
862        1800.0
863        5481.0
864        1728.0
865        1449.0
866        2700.0
867        1620.0
868        3240.0
869        3240.0
870        1800.0
871        1850.0
872        1950.0
873        2430.0
874        2844.0
875        3240.0
876        3600.0
877        9000.0
878        1800.0
879        3159.0
880        2520.0
881        2844.0
882        5580.0
883        3191.0
884        2700.0
885        4518.0
886        4500.0
887        1440.0
888        1620.0
889        2160.0
890        4235.0
891        8036.0
892        1557.0
893        1450.0
894        1352.0
895        1187.0
896        1450.0
897        3323.0
898        4500.0
899        1450.0
900        1187.0
901        2700.0
902        8116.0
903        5608.0
904        3240.0
905        3078.0
906         918.0
907        7000.0
908        2592.0
909        3240.0
910        2430.0
911        6000.0
912        2642.0
913         251.0
914        1350.0
915        2250.0
916        2700.0
917        1800.0
918        2610.0
919        1620.0
920           NaN
921        1350.0
922        7000.0
923        4950.0
924        2403.0
925         546.0
926        2340.0
927        2340.0
928         275.0
929        6228.0
930        4680.0
931        1728.0
932        2700.0
933        3200.0
934        2250.0
935        2367.0
936        1440.0
937       10000.0
938        1935.0
939        2034.0
940        1800.0
941        1800.0
942        2844.0
943        5018.0
944        1800.0
945        2592.0
946        1230.0
947        2340.0
948        1620.0
949         160.0
950        1620.0
951        1836.0
952        9000.0
953        1700.0
954        3240.0
955        4518.0
956        4235.0
957         540.0
958        4050.0
959        3096.0
960        1701.0
961        1530.0
962        1350.0
963        1935.0
964        2844.0
965        2700.0
966        2160.0
967        3375.0
968        2088.0
969         232.0
970        1467.0
971        1170.0
972        1836.0
973        3150.0
974        1935.0
975        2160.0
976        4518.0
977        2592.0
978        4000.0
979        2727.0
980        4500.0
981        2700.0
982        4518.0
983        2088.0
984        4050.0
985        3240.0
986        3420.0
987        4000.0
988        3240.0
989         300.0
990        2430.0
991        3240.0
992        2160.0
993        3240.0
994        3456.0
995        2160.0
996        6228.0
997        2368.0
998        3370.0
999        5400.0
1000       4770.0
1001       1845.0
1002       1265.0
1003          NaN
1004       1458.0
1005        126.0
1006        585.0
1007       4680.0
1008       1458.0
1009       2160.0
1010       2844.0
1011       5056.0
1012       1350.0
1013       1400.0
1014       2430.0
1015       4125.0
1016       1494.0
1017       2160.0
1018       2160.0
1019       1935.0
1020       1926.0
1021       1809.0
1022       1125.0
1023          NaN
1024          NaN
1025       1449.0
1026       1800.0
1027        900.0
1028       1548.0
1029       1836.0
1030       2367.0
1031        909.0
1032       1449.0
1033       2367.0
1034       1449.0
1035       1449.0
1036       1548.0
1037       1650.0
1038       2430.0
1039       1800.0
1040       1350.0
1041       1350.0
1042        981.0
1043       2430.0
Name: area, dtype: float64

In [107]:
df['area'].isnull().sum()

19